"""The `.fux/` directory — one declared layout, committed vs derived.

Every child of `.fux/` is declared here as **committed** (belongs in git —
the index, the source lists, the consumer's middleware) or **derived**
(rebuildable, gitignored, self-tagged). Nothing else should appear there;
`fux doctor` warns on anything undeclared, which is how a plane added by
accident gets noticed before it is committed.

Two rules make the split safe to live under a single dotdir:

- **`.fux/.gitignore` lists derived directory names explicitly, never `*`.**
  A blanket ignore plus an unignore is exactly how a committed plane goes
  missing silently; `fux doctor` asserts `git check-ignore` disagrees about
  `.fux/index`.
- **Derived directories carry `CACHEDIR.TAG`** ([the spec](https://bford.info/cachedir/)),
  so backup and archiving tools skip them without being told. Same pattern
  pytest uses for `.pytest_cache` (it writes `CACHEDIR.TAG` + `.gitignore` +
  `README.md` into its own cache dir) and mypy for `.mypy_cache`.

Consumer files are **write-if-missing, never overwritten**: `README.md` and
`.gitignore` may be annotated freely and fux will not clobber the edit. All
generated bytes are plain ASCII with explicit `\\n` — no wall-clock, no
locale, no console-encoding surprises on Windows.

See ADR-0011.
"""

from __future__ import annotations

from pathlib import Path

FUX_DIR = ".fux"

#: Declared children of `.fux/` — name -> one-line description for the README.
COMMITTED: dict[str, str] = {
    "index": "the wire-format index (ADR-0004)",
    "sources": "large line-oriented source lists (`urls`; M4 may add more)",
    "middleware": "consumer-owned code (`cdp.py`), edit freely",
}

DERIVED: dict[str, str] = {
    "runtime": "reserved for M2 accelerator segments",
    "cache": "reserved for M4 ARC fetch cache",
}

#: Files fux generates at the top level of `.fux/` (write-if-missing).
GENERATED_FILES = ("README.md", ".gitignore")

#: Everything legally found directly under `.fux/`; anything else is a warning.
DECLARED = (*COMMITTED, *DERIVED, *GENERATED_FILES)

# CACHEDIR.TAG's first line is a fixed signature — byte-exact, per the spec.
CACHEDIR_SIGNATURE = "Signature: 8a477f597d28d172789f06886806bc55"
CACHEDIR_TAG = (
    f"{CACHEDIR_SIGNATURE}\n"
    "# This file is a cache directory tag created by fux.\n"
    "# For information about cache directory tags, see https://bford.info/cachedir/\n"
)

_GITIGNORE = (
    "# Derived planes only: rebuildable from the committed index and the\n"
    "# source systems. NEVER add `*` here: `.fux/index/`, `.fux/sources/` and\n"
    "# `.fux/middleware/` are committed, and a blanket ignore would drop them\n"
    "# from git silently. `fux doctor` checks exactly that.\n"
    + "".join(f"{name}/\n" for name in DERIVED)
)


def _readme() -> str:
    # Plain ASCII on purpose: no em-dashes, no smart quotes. These bytes get
    # printed and diffed on Windows consoles whose codepage cannot encode them.
    rows = [
        "# `.fux/`",
        "",
        "Fux's directory in your repo. Every child is declared below as",
        "**committed** (belongs in git) or **derived** (rebuildable, ignored,",
        "tagged with [`CACHEDIR.TAG`](https://bford.info/cachedir/)).",
        "",
        "| entry | kind | what it is |",
        "|---|---|---|",
        "| `README.md` | committed | this file: written once by fux, yours to annotate |",
        "| `.gitignore` | committed | lists only the derived directories, never `*` |",
    ]
    rows += [f"| `{name}/` | committed | {desc} |" for name, desc in COMMITTED.items()]
    rows += [f"| `{name}/` | derived | {desc}; carries `CACHEDIR.TAG` |" for name, desc in DERIVED.items()]
    rows += [
        "",
        "## The middleware is yours",
        "",
        "`middleware/cdp.py` is **your** code, committed to **your** repo. Fux",
        "loads it by path under `fux ingest --refresh-urls` and never rewrites",
        "it. Change the port, the transport, the extraction, anything.",
        "",
        "One consequence of living in a dotdir: linters that skip hidden",
        "directories by default (ruff does) will not lint it. That is fine, it",
        "is consumer code, not a CI target.",
        "",
        "## Rules",
        "",
        "- Anything here that is not in the table above is undeclared; `fux",
        "  doctor` warns about it.",
        "- Derived directories can be deleted at any time; committed ones",
        "  cannot be rebuilt from anything but their source systems.",
        "- Fux writes `README.md` and `.gitignore` **only if missing**. Your",
        "  edits survive every ingest.",
        "",
    ]
    return "\n".join(rows)


def fux_dir(root: Path) -> Path:
    return root / FUX_DIR


def ensure_layout(root: Path) -> list[Path]:
    """Create `.fux/` and its generated files if absent; return what was written.

    Idempotent and non-destructive: an existing `README.md`/`.gitignore` is
    left exactly as the consumer edited it.
    """
    directory = fux_dir(root)
    directory.mkdir(parents=True, exist_ok=True)
    written: list[Path] = []
    for name, text in (("README.md", _readme()), (".gitignore", _GITIGNORE)):
        path = directory / name
        if not path.exists():
            path.write_bytes(text.encode("ascii"))
            written.append(path)
    return written


def derived_dir(root: Path, name: str) -> Path:
    """Return `.fux/<name>/`, created and tagged as a cache directory.

    For M2/M4 to call when they materialize `runtime/` and `cache/`. The tag
    is written once and never overwritten.
    """
    path = fux_dir(root) / name
    path.mkdir(parents=True, exist_ok=True)
    tag = path / "CACHEDIR.TAG"
    if not tag.exists():
        tag.write_bytes(CACHEDIR_TAG.encode("ascii"))
    return path
