"""The `.fux/` directory — one declared layout, committed vs derived.

Every child of `.fux/` is declared here as **committed** (belongs in git —
the index, the source lists, the consumer's fetcher) or **derived**
(rebuildable, gitignored, self-tagged). Nothing else should appear there;
`fux doctor` warns on anything undeclared, which is how a plane added by
accident gets noticed before it is committed.

Two rules make the split safe to live under a single dotdir:

- **`.fux/.gitignore` lists derived directory names explicitly, never `*`.**
  A blanket ignore plus an unignore is exactly how a committed plane goes
  missing silently; `fux doctor` asserts `git check-ignore` disagrees about
  `.fux/index`.
- **Derived directories carry `CACHEDIR.TAG`** ([the spec](https://bford.info/cachedir/)),
  so backup and archiving tools skip them without being told. Same pattern
  pytest uses for `.pytest_cache` (it writes `CACHEDIR.TAG` + `.gitignore` +
  `README.md` into its own cache dir) and mypy for `.mypy_cache`.

Consumer files are **write-if-missing, never overwritten**: `README.md` and
`.gitignore` may be annotated freely and fux will not clobber the edit. All
generated bytes are plain ASCII with explicit `\\n` — no wall-clock, no
locale, no console-encoding surprises on Windows.

See SR-DOTFUX.
"""

from __future__ import annotations

from pathlib import Path

FUX_DIR = ".fux"

#: Declared children of `.fux/` — name -> one-line description for the README.
COMMITTED: dict[str, str] = {
    "index": "the wire-format index (SR-RECORD)",
    "sources": "the committed source lists (`dirs`, `urls`), one entry per line",
    "fetchers": "consumer-owned code (`cdp.py`, `http.py`), edit freely",
    # ASCII only: `_readme()` encodes this table as ASCII on purpose, for
    # Windows consoles. An em-dash here fails the write, which is how this was
    # caught rather than shipped.
    "decoders": "consumer-owned code, one module per format. THESE COPIES ARE WHAT RUN, not the ones inside the installed package (SR-DECODE)",
    # ASCII only, like every value in this table.
    "observers": "consumer-owned code, one module per subscriber. Called AFTER a verb has fully rendered, with one record of COUNTS -- never the question, a path, or the answer. It cannot change an answer: no return path, and the dispatch runs after every write (SR-OBSERVE)",
    "enrich": "pinned enrichment text, one file per source content sha, plus `queue.tsv` (W-86 P6: what fux could NOT read and a model must). Committed, because a backlog is a team fact",
    # ASCII only, like every other value in these tables.
    "node": "the Node read plane (`fux-engine`) as ONE BUNDLED FILE plus its manifest -- build output, never fux's source (L10). Engine-owned and REWRITTEN on a version change, not write-if-missing, because nobody edits it and a stale copy is a wrong answer. In a monorepo it is a workspace member holding only a manifest (SR-NODE-SEARCH)",
}

#: Gitignored like DERIVED, and NOT rebuildable -- which is exactly why it is
#: not filed there. `runtime/` means "fux build can reconstruct this"; an
#: acquired blob can only be re-ACQUIRED, and only while the source still
#: exists and the session that reached it still holds (SR-ACQUIRED).
ACQUIRED: dict[str, str] = {
    # ASCII only, like every other value in these tables.
    "acquired": "the bytes a fetch actually returned, for URLs whose line says keep=true. Gitignored and NOT rebuildable - re-acquirable only, and only while the source is still reachable; carries CACHEDIR.TAG",
}

DERIVED: dict[str, str] = {
    "runtime": "M2 accelerator segments, M4's fetch cache at `runtime/fetch-cache/`, the write lock, and `enrich-progress.tsv` (W-86 P6: which queued documents THIS machine has handled - local by design, so two people's progress cannot conflict on a pull)",
}

#: Files fux generates at the top level of `.fux/` (write-if-missing).
GENERATED_FILES = ("README.md", ".gitignore")

#: Committed FILES at the top level, as opposed to committed directories.
#:
#: **This tuple exists because its absence was a live defect.** `DECLARED` was
#: built from `COMMITTED` (directories), `DERIVED` and `GENERATED_FILES`, so a
#: committed *file* had no row anywhere and `fux doctor` reported it as an
#: undeclared entry — SR-DOTFUX veto condition 1, firing. `tune.toml` would
#: have shipped into that warning on day one; `.fux/enrich/` was already in it.
#: Found 2026-08-24 by checking the claim instead of asserting it.
COMMITTED_FILES: dict[str, str] = {
    "tune.toml": "the tunables: HOW results are ordered, never what is indexed (SR-TUNE)",
    "output.toml": "the output defaults: HOW a result is SHOWN, never which documents come back (SR-OUTPUT)",
    # ASCII only, like every other value in these tables.
    "formats.toml": "which files are documents (`include`) and which decoder reads each extension (`[decoders]`). Optional - absent means the built-in default. Replaced .fux/sources/types on 2026-09-11 (SR-TYPES)",
    # ASCII only, like every other value in these tables -- `_readme()` encodes
    # them for a Windows console.
    ".fuxignore": "what is NOT indexed, in .gitignore's grammar. The one place exclusions belong, read before the source lists (SR-FUXIGNORE)",
    # ASCII only, like every other value in these tables.
    # ASCII only, like every other value in these tables.
    "pii.toml": "REQUIRED - every command refuses without it. What is REDACTED from the committed index - and ONLY from it. The acquired bytes, the refer plane and every answer quote still see the document as it is (SR-PII)",
    "refusals.toml": "what a REFUSAL looks like here - the sign-in walls, paywalls and error shells a server returns INSTEAD of the document. Consumer-owned; fux ships no vendor knowledge (SR-REFUSAL)",
    # ASCII only, like every other value in these tables.
    "fux": "the shim: `.fux/fux find rollback` in a clone with nothing installed. Resolves the reader in three rungs -- the vendored bundle, this member's `node_modules/.bin`, then every ancestor's -- because npm and yarn hoist that bin and pnpm and bun do not (SR-NODE-SEARCH)",
}

#: Everything legally found directly under `.fux/`; anything else is a warning.
DECLARED = (*COMMITTED, *COMMITTED_FILES, *DERIVED, *ACQUIRED, *GENERATED_FILES)

# CACHEDIR.TAG's first line is a fixed signature — byte-exact, per the spec.
CACHEDIR_SIGNATURE = "Signature: 8a477f597d28d172789f06886806bc55"
CACHEDIR_TAG = (
    f"{CACHEDIR_SIGNATURE}\n"
    "# This file is a cache directory tag created by fux.\n"
    "# For information about cache directory tags, see https://bford.info/cachedir/\n"
)

_GITIGNORE = (
    "# Gitignored planes, BY NAME. NEVER add `*` here: `.fux/index/`,\n"
    "# `.fux/sources/`, `.fux/fetchers/`, `.fux/decoders/` and\n"
    "# `.fux/observers/` are committed,\n"
    "# and a blanket ignore would drop them from git silently. `fux doctor`\n"
    "# checks exactly that.\n"
    "#\n"
    "# `runtime/` is DERIVED: rebuildable from the committed index by\n"
    "# `fux build`. `acquired/` is not -- it holds the bytes a fetch actually\n"
    "# returned, which can only be re-acquired while the source is still\n"
    "# reachable. Both are ignored; only one can be regenerated.\n"
    + "".join(f"{name}/\n" for name in DERIVED)
    + "".join(f"{name}/\n" for name in ACQUIRED)
    # ⚠ **Not a plane -- CPython's litter beside the committed Python**
    # (W-140 row 18, 2026-09-11). `fux setup` writes real modules into
    # `.fux/decoders/` and `.fux/fetchers/` and ingest imports them, so
    # `__pycache__/` appears next to files a consumer is supposed to commit.
    # Every repo whose own .gitignore happens to carry the Python line was
    # fine; one that does not sees untracked bytecode in the directory fux
    # just told them to commit. By NAME, like everything else here, and
    # matching at any depth under `.fux/` is exactly the scope wanted.
    + "__pycache__/\n"
    # ⚠ **Not a plane either -- a package manager's install directory**, which
    # only exists in the monorepo shape, where `.fux/node` is a workspace member
    # and the reader is INSTALLED rather than vendored (SR-NODE-SEARCH
    # decision 13, shape C). By path rather than by name: `node_modules/` alone
    # would also ignore one a consumer keeps elsewhere under `.fux/`, and this
    # file's whole discipline is that nothing is ignored by accident.
    + "node/node_modules/\n"
    # 🔴 **The transient a WRITE leaves in a COMMITTED directory** (W-185,
    # 2026-09-15). `store/writer.py::_atomic_write` writes
    # `index/<shard>.jsonl.tmp` beside the shard and renames it -- the sibling
    # is required, because `os.replace` is atomic only within one filesystem.
    # `post-commit` DEFERS (SR-MAINTENANCE decision 1a), so a consumer's next
    # `git add -A` legitimately overlaps a live writer, lists the temp file, and
    # then cannot stat it:
    #
    #     fatal: unable to stat '.fux/index/ad.jsonl.tmp': No such file or directory
    #
    # ⚠ **This line IS the fix, and it was measured rather than argued.** A
    # controlled probe -- the same rename churn, with and without the rule --
    # gives **0 failures in 3 871 `git add -A` runs ignored** against **2 335 of
    # 3 933 unignored**. The earlier reasoning that an ignore rule "cannot close
    # the window because git stats what it listed" is wrong: an excluded path is
    # never walked.
    #
    # **Scoped to the plane and to the suffix**, never `*.tmp` and never `*`:
    # this file's whole discipline is that nothing is ignored by accident, and a
    # bare `*.tmp` would also hide a consumer's own file anywhere under `.fux/`.
    + "index/*.jsonl.tmp\n"
)


def _readme() -> str:
    # Plain ASCII on purpose: no em-dashes, no smart quotes. These bytes get
    # printed and diffed on Windows consoles whose codepage cannot encode them.
    rows = [
        "# `.fux/`",
        "",
        "Fux's directory in your repo. Every child is declared below, in one",
        "of THREE kinds:",
        "",
        "- **committed** - belongs in git. This is the product.",
        "- **derived** - rebuildable from the committed bytes by `fux build`.",
        "  Ignored, tagged with [`CACHEDIR.TAG`](https://bford.info/cachedir/),",
        "  and safe to delete at any time.",
        "- **acquired** - the bytes a fetch returned. Ignored and tagged like",
        "  derived, but NOT rebuildable: deleting it loses the only local copy,",
        "  and getting it back means re-fetching from a source that must still",
        "  exist and a session that must still hold.",
        "",
        "| entry | kind | what it is |",
        "|---|---|---|",
        "| `README.md` | committed | this file: written once by fux, yours to annotate |",
        "| `.gitignore` | committed | lists the ignored directories BY NAME, never `*` |",
    ]
    rows += [f"| `{name}/` | committed | {desc} |" for name, desc in COMMITTED.items()]
    rows += [f"| `{name}` | committed | {desc} |" for name, desc in COMMITTED_FILES.items()]
    rows += [f"| `{name}/` | derived | {desc}; carries `CACHEDIR.TAG` |" for name, desc in DERIVED.items()]
    rows += [f"| `{name}/` | acquired | {desc} |" for name, desc in ACQUIRED.items()]
    rows += [
        "",
        "## The fetchers are yours",
        "",
        "`fetchers/http.py` and `fetchers/cdp.py` are **your** code, committed",
        "to **your** repo. `fux setup` writes them once if they are missing;",
        "`fux ingest` never writes a fetcher at all. Fux loads one by path",
        "under `fux add <URL>` or `fux update`, and never rewrites it. Change the",
        "port, the transport, the extraction, anything.",
        "",
        "One consequence of living in a dotdir: linters that skip hidden",
        "directories by default (ruff does) will not lint it. That is fine, it",
        "is consumer code, not a CI target.",
        "",
        "## Rules",
        "",
        "- Anything here that is not in the table above is undeclared; `fux",
        "  doctor` warns about it.",
        "- Derived directories can be deleted at any time. Committed ones",
        "  cannot be rebuilt from anything but their source systems.",
        "- `acquired/` sits between the two: deleting it costs you the local",
        "  copy of bytes you already fetched, and a re-fetch is the only way",
        "  back. `fux doctor` reports its size.",
        "- Fux writes `README.md` and `.gitignore` **only if missing**. Your",
        "  edits survive every ingest.",
        "",
        "---",
        "",
        "# What fux is",
        "",
        "A search index for your written knowledge - decisions, runbooks,",
        "specs, wiki pages - committed to git and read by agents.",
        "",
        "- **The index is committed; the content is not.** `index/` holds",
        "  statistics about your documents, never the documents. That is why",
        "  it diffs like code and why no second copy of anything exists.",
        "- **Ranking is arithmetic.** BM25F, one scorer, one sort. The same",
        "  sources build the same index, byte for byte, on any machine.",
        "- **No server, no vector database, no API key, and no model anywhere",
        "  on the path.** `fux ask` is a local process reading local files.",
        "- **It does not read your code.** No parser runs over source files,",
        "  and no source extension is on the default type list. Fux is about",
        "  what you wrote down, not what you compiled.",
        "- **Answers are re-read before they are quoted.** `fux answer` fetches",
        "  the cited lines from the source and tells you whether they still",
        "  say what the index thinks they say.",
        "",
        "# The commands",
        "",
        "Flat verbs, no subcommand tree. `fux <verb> --help` for any of them.",
        "",
        "| group | verbs | what the group does |",
        "|---|---|---|",
        "| lifecycle | `setup` `doctor` `inspect` | set the repo up, check the environment, then X-ray the index it produced |",
        "| write | `ingest` `build` | `ingest` writes the committed index; `build` derives the local accelerator from it |",
        "| sources | `add` `remove` `update` `enrich` `correct` | maintain what is indexed. `add`/`remove` write lines; `update` re-fetches and writes none; `enrich` plans and validates a model's text; `correct` writes one question a PERSON typed onto the document that answers it |",
        "| read | `ask` `find` `answer` `lexical` | the same question, differing only in how much each commits to. `lexical` is BM25F alone, frozen - the baseline `ask` is measured against |",
        "| graph | `explain` `graph` `path` | answer with relationships the documents stated, never with a ranking |",
        "| serve | `mcp` `daemon` | the only verbs that do not return |",
        "| maintenance | `hooks` `tune` `output` `verify` | wire git to keep the index in step; print or set the tunables; re-run a receipt |",
        "",
        "**The three read verbs differ in how much they commit to.** `find`",
        "gives locations and stays out of the way. `ask` gives a ranked list",
        "with scores, which is what you want when judging the engine. `answer`",
        "commits to one passage with a line range and a freshness verdict,",
        "which is what an agent wants when it needs a value and not a menu.",
        "",
        "```console",
        "$ fux setup                 # write the consumer-owned files here",
        "$ fux add docs/             # index a directory",
        "$ fux add https://wiki/...  # index a URL through a fetcher you own",
        "$ fux ingest                # walk the sources into the committed index",
        "$ fux doctor                # is this repo healthy, and why not",
        "",
        "$ fux find rollback                       # one line per hit, for pipes",
        "$ fux ask 'how do we roll back a release' # ranked, with scores",
        "$ fux answer 'what is the RTO' --band     # one passage, cited and checked",
        "```",
        "",
        "# Calling fux from a script, in any language",
        "",
        "**There is no SDK, and that is the design.** Fux is a normal",
        "command-line program: it reads files, writes to stdout, and exits with",
        "a status. Anything that can start a process can drive it, which is why",
        "there is no binding to install, version, or wait for.",
        "",
        "**Three things are the whole contract:**",
        "",
        "1. **`--json` on every read verb.** `ask`, `find`, `answer`, `explain`,",
        "   `graph`, `path`, `doctor`, `update`. Never parse the prose output -",
        "   it is for humans and it is allowed to change.",
        "2. **Exit codes.** `0` ok - `1` error - `2` blocking (strict mode) -",
        "   `130` interrupted. Errors go to stderr as `error: <message>`.",
        "3. **It is offline and deterministic.** No network on a read path, so a",
        "   call is fast enough to make inline and safe to make in a loop.",
        "",
        "**The JSON shape you will actually use:**",
        "",
        "```json",
        "{ \"results\": [ { \"id\": \"docs/runbook.md\",",
        "                 \"title\": \"Release runbook\",",
        "                 \"score\": 12.41,",
        "                 \"headings\": [\"Rollback\"] } ],",
        "  \"confidence\": { \"band\": \"high\", \"answerable\": true, \"missing\": [] } }",
        "```",
        "",
        "`confidence` is present only when you pass `--band`. **Absent means",
        "not asked for; it is never a claim about the answer.**",
        "",
        "## Shell",
        "",
        "```bash",
        "fux ask 'retention policy' --json | jq -r '.results[0].id'",
        "",
        "# exit code first, output second",
        "if ! fux doctor --json > health.json; then",
        "  echo \"index unhealthy\" >&2; exit 1",
        "fi",
        "```",
        "",
        "## Python",
        "",
        "```python",
        "import json, subprocess",
        "",
        "def ask(question, top=5):",
        "    p = subprocess.run(",
        "        [\"fux\", \"ask\", question, \"--json\", \"--top\", str(top), \"--band\"],",
        "        capture_output=True, text=True, encoding=\"utf-8\",",
        "    )",
        "    if p.returncode != 0:",
        "        raise RuntimeError(p.stderr.strip())",
        "    return json.loads(p.stdout)",
        "",
        "hits = ask(\"how do we roll back a release\")",
        "if hits.get(\"confidence\", {}).get(\"answerable\"):",
        "    print(hits[\"results\"][0][\"id\"])",
        "```",
        "",
        "Import `fux` as a library only if you accept that the Python API is",
        "not a supported surface. **The CLI is the contract; the modules are",
        "not.**",
        "",
        "## Node / TypeScript",
        "",
        "```js",
        "import { execFile } from 'node:child_process';",
        "import { promisify } from 'node:util';",
        "const run = promisify(execFile);",
        "",
        "export async function ask(question, top = 5) {",
        "  const { stdout } = await run('fux',",
        "    ['ask', question, '--json', '--top', String(top), '--band']);",
        "  return JSON.parse(stdout);",
        "}",
        "```",
        "",
        "A non-zero exit rejects the promise and carries `stderr`, so the error",
        "path needs no special handling.",
        "",
        "## Go, Ruby, Rust, anything else",
        "",
        "Same three steps every time, because there is nothing language-",
        "specific to learn:",
        "",
        "1. Spawn `fux` with the verb, the query, and `--json`.",
        "2. Check the exit status; read `stderr` when it is non-zero.",
        "3. Parse `stdout` as JSON.",
        "",
        "```go",
        "out, err := exec.Command(\"fux\", \"ask\", q, \"--json\").Output()",
        "// err is *exec.ExitError on a non-zero status; out is the payload",
        "```",
        "",
        "## For an AI agent",
        "",
        "Two ways in, and they differ in who owns the loop:",
        "",
        "- **`fux mcp`** - serves the index over the Model Context Protocol",
        "  (`fux_search`, `fux_passage`, `fux_related`). The client calls the",
        "  tools; you configure the server once and write no glue.",
        "- **A skill or instruction file** - `fux setup` installs guides for",
        "  Claude Code, Codex, Copilot and Kiro that tell the agent to query",
        "  the index rather than grep. The agent shells out to the CLI.",
        "",
        "Use MCP when the client speaks it. Use the CLI everywhere else; it is",
        "the same engine either way.",
        "",
        "## One rule for every caller",
        "",
        "**`fux answer` re-reads the source before it quotes.** Its verdict",
        "field says `current`, `stale`, `as-ingested`, `cached` or `unverified`",
        "- and a script that ignores that field has thrown away the only thing",
        "separating fux from a stale cache with good manners.",
        "",
    ]
    return "\n".join(rows)


def fux_dir(root: Path) -> Path:
    return root / FUX_DIR


def ensure_layout(root: Path, *, node_shape: "str | None" = None) -> list[Path]:
    """Create `.fux/` and its generated files if absent; return what was written.

    Idempotent and non-destructive: an existing `README.md`/`.gitignore` is
    left exactly as the consumer edited it.

    ⚠ **`node_shape` is `setup`'s to pass and nobody else's.** This function
    runs at the head of **every ingest**, and the shape is decided by looking at
    the consumer's repository — a detection that must happen once, in `setup`,
    not on every run (SR-NODE-SEARCH decision 15 constraint 1). Left `None`,
    the shape already on disk is kept.
    """
    directory = fux_dir(root)
    directory.mkdir(parents=True, exist_ok=True)
    written: list[Path] = []
    for name, text in (("README.md", _readme()), (".gitignore", _GITIGNORE)):
        path = directory / name
        if not path.exists():
            path.write_bytes(text.encode("ascii"))
            written.append(path)
    written.extend(ensure_node_reader(root, shape=node_shape))
    return written


# ---------------------------------------------------------------------------
# The vendored Node reader -- SR-NODE-SEARCH decisions 13-16, L10.
#
# **The fourth shape under SR-DOTFUX**: committed, engine-owned, and
# OVERWRITTEN -- not write-if-missing. `fetchers/` and `decoders/` are
# write-if-missing because a consumer EDITS them; nobody edits a vendored
# reader, and a stale one against a bumped `_format` is a WRONG ANSWER rather
# than an old preference.
#
# The evidence this is the right call is in this repo: `.fux/decoders/` is
# write-if-missing, and the `doc`-suffix rename (2026-09-06) shipped with no
# migration -- a repo set up before it still holds stale `<name>doc.py` files
# that claim the same extensions and WIN.
#
# 🔴 **What a consumer gets is BUILD OUTPUT, and since 2026-09-12 that is a
# law** ([L10](../../../records/0011_LAW-10-bundled-output.md)). The 47-file
# module tree this code used to write is gone, in two shapes:
#
#   A  the bundle, vendored   -- `package.json`, `fux.mjs`, `mcp-tools.json`,
#                                `README.md`. Offline, no install, the default.
#   C  a workspace member     -- `package.json` only, declaring
#                                `fux-engine@<version>`; the reader resolves
#                                out of `node_modules` after an install.
#
# **The prune is part of the decision, not a follow-up.** Without it every
# repository that ever ran `fux setup` keeps its stale `src/**` for good.
# ---------------------------------------------------------------------------

#: The vendored Node reader. Committed (a clone with no Python still answers)
#: and rewritten whenever the engine version differs, so a `_format` mismatch
#: cannot happen: the copy is always written by the Python that wrote the index.
NODE_DIR = "node"
NODE_ENTRY = "fux.mjs"
NODE_SHIM = "fux"

#: The two shapes of `.fux/node/`. Spelled "A" and "C" because those are the
#: labels the ruling used and the record carries (SR-NODE-SEARCH decision 13);
#: B was a third option nobody chose and the letters are not renumbered, so a
#: reader of the record and a reader of this file are talking about one thing.
SHAPE_VENDORED = "A"
SHAPE_WORKSPACE = "C"

#: What `node_modules/` is called, and the ONE thing the prune never touches.
#: In shape C it holds the installed reader; deleting it would leave a manifest
#: pointing at nothing, which is decision 15's "half-configured is not a state"
#: arriving through the back door.
_NODE_MODULES = "node_modules"

#: `chmod` bits for the shim -- readable and executable by everyone who can read
#: the repo, which is the same set that can read the index it queries.
_SHIM_MODE = 0o755

_SHIM = """#!/bin/sh
# Vendored by `fux setup`. Runs the Node read plane against this repository.
# The command is `fux`; the npm package is `fux-engine` (`fux` was taken in
# 2016). This shim exists so a clone needs nothing installed at all.
#
# **Three rungs, because the binary is not in one place.** MEASURED across
# npm, pnpm, yarn 1 and bun (work/regression/2026-09-12-workspace-dotpath-probe):
# npm and yarn HOIST `fux` to the workspace root's `node_modules/.bin`, pnpm and
# bun leave it in the member's own. A shim naming either one would be right for
# half the ecosystem and silently wrong for the other half, so it tries, in
# order: the vendored bundle, this member's bin, then every ancestor's.
dir=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)

# 1 - shape A: the bundle `fux setup` vendored. Offline, nothing installed.
if [ -f "$dir/node/fux.mjs" ]; then
  exec node "$dir/node/fux.mjs" "$@"
fi

# 2 - shape C under pnpm or bun: the bin stays in the member.
if [ -x "$dir/node/node_modules/.bin/fux" ]; then
  exec "$dir/node/node_modules/.bin/fux" "$@"
fi

# 3 - shape C under npm or yarn: the bin is hoisted to the workspace root.
d=$dir
while [ "$d" != "/" ]; do
  if [ -x "$d/node_modules/.bin/fux" ]; then
    exec "$d/node_modules/.bin/fux" "$@"
  fi
  d=$(dirname -- "$d")
done

echo "fux: no Node reader here. This repository declares .fux/node as a" >&2
echo "     workspace member (shape C), so run your package manager's install" >&2
echo "     first -- or run 'fux setup' outside a monorepo to vendor the bundle." >&2
exit 1
"""


def _node_source():
    """The directory the vendored reader is copied FROM.

    Two locations, one source. The wheel carries the BUNDLE at
    `fux/templates/node/` (built at publish -- `pyproject.toml`'s build hook),
    so an installed fux reads it as package data: the same contract
    `templates/` has, bytes and never an import.

    ⚠ **An EDITABLE install has no such payload**, because the hook maps the
    directory at BUILD time and an editable install never builds one. The
    fallback is the checkout's own `node/`, which is the module tree the bundle
    is built FROM -- and there `_packaged_node_files` builds it rather than
    copying, because *"silently vendoring `node/src/**` in development and the
    bundle in release is two products wearing one version"*
    (SR-NODE-SEARCH decision 14).
    """
    from importlib import resources

    packaged = resources.files("fux") / "templates" / NODE_DIR
    if packaged.is_dir():
        return packaged
    checkout = Path(__file__).resolve().parents[3] / NODE_DIR
    if checkout.is_dir():
        return checkout
    from ..errors import FuxError

    raise FuxError(
        "the Node read plane is missing from this installation: neither "
        "`fux/templates/node/` (the wheel) nor a `node/` directory beside "
        "`src/` was found. Reinstall fux, or run from a checkout."
    )


def _packaged_node_files() -> "list[tuple[str, bytes]]":
    """`(relative path, bytes)` for shape A's payload -- the bundle + sidecars.

    Two cases, and the difference is deliberate rather than incidental:

    - **A release install** carries the already-built payload at
      `fux/templates/node/`. Four files, copied.
    - **A checkout** carries the module tree, which is NOT what a consumer may
      be served (L10). The bundle is BUILT here, from those sources, so `fux
      setup` in development writes exactly what a release writes.

    🔴 **It never falls back to copying `src/**`.** A checkout whose sources the
    bundler cannot read raises out of `nodebundle`, with the reason -- decision
    14's *"builds the bundle or refuses with a message saying so"*.
    """
    source = _node_source()
    if isinstance(source, Path) and (source / "src").is_dir():
        from . import nodebundle

        return nodebundle.bundle_files(source)

    out: list[tuple[str, bytes]] = []

    def walk(node, prefix: str = "") -> None:
        for child in sorted(node.iterdir(), key=lambda c: c.name):
            rel = f"{prefix}{child.name}"
            if child.is_dir():
                walk(child, rel + "/")
            else:
                out.append((rel, child.read_bytes()))

    walk(source)
    if any(rel.startswith("src/") for rel, _ in out):
        from ..errors import FuxError

        raise FuxError(
            "this installation of fux carries the Node reader as a module tree rather than "
            "the published bundle, so `fux setup` would write fux's source into your "
            "repository (L10). Reinstall `fux-engine` from a release, or run from a checkout."
        )
    return out


def _workspace_manifest(version: str) -> bytes:
    """Shape C's whole payload: a manifest naming the published reader.

    ⚠ **This is the one `package.json` fux writes that HAS a `dependencies`
    key**, and it is not an L1 problem: the dependency is fux itself, pinned to
    the exact version that wrote the index -- the same guarantee shape A gets by
    carrying the bundle. `private: true` so a `npm publish` at the workspace
    root can never push a consumer's reader stub to the registry.
    """
    import json

    return json.dumps(
        {
            "name": "fux-reader",
            "private": True,
            "version": version,
            "description": (
                "This repository's fux read plane, resolved from npm. Written by `fux setup`, "
                "which detected a monorepo. Run it through ../fux, never by path."
            ),
            "dependencies": {"fux-engine": version},
        },
        indent=2,
    ).encode("utf-8") + b"\n"


def node_version(directory: Path) -> "str | None":
    """The version of the vendored reader, or `None` when it is absent.

    Read from `package.json` rather than from a sidecar: one file, and it is
    the file npm would read too, so a consumer who vendored by hand and a
    consumer who ran `fux setup` are compared the same way.
    """
    import json

    path = directory / NODE_DIR / "package.json"
    if not path.is_file():
        return None
    try:
        return json.loads(path.read_text(encoding="utf-8")).get("version")
    except (OSError, ValueError):
        return None


def node_shape(directory: Path) -> "str | None":
    """Which shape `.fux/node/` is in, read off the directory itself.

    **Self-describing state, rather than a fifth config file.** Shape C's
    manifest declares `fux-engine` as a dependency and shape A's never does, so
    the payload answers the question — and a consumer who switches by hand gets
    the shape they actually created, not one a sidecar remembers.
    """
    import json

    path = directory / NODE_DIR / "package.json"
    if not path.is_file():
        return None
    try:
        meta = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, ValueError):
        return None
    deps = meta.get("dependencies")
    if isinstance(deps, dict) and "fux-engine" in deps:
        return SHAPE_WORKSPACE
    return SHAPE_VENDORED


def _prune_node_reader(target: Path, keep: "set[str]") -> "list[Path]":
    """Delete everything under `.fux/node/` that the declared shape does not
    name, `node_modules/` excepted. Returns what was removed.

    🔴 **The half that did not exist until 2026-09-12.** `ensure_node_reader`
    wrote on a version difference and deleted nothing, so a repository set up
    before this change keeps its 37-47 stale `.mjs` files — and they are not
    inert: `.fux/node/src/query/rank.mjs` is a complete, editable ranker that
    the old entry point would import.
    """
    removed: list[Path] = []
    if not target.is_dir():
        return removed
    for path in sorted(target.rglob("*"), key=lambda p: len(p.parts), reverse=True):
        rel = path.relative_to(target).as_posix()
        if rel == _NODE_MODULES or rel.startswith(_NODE_MODULES + "/"):
            continue
        if path.is_dir():
            if not any(path.iterdir()):
                path.rmdir()
                removed.append(path)
        elif rel not in keep:
            path.unlink()
            removed.append(path)
    return removed


def _expected_layout(shape: str) -> "set[str]":
    """The file names the declared shape should hold — WITHOUT building anything.

    Named from `nodebundle`'s constants rather than from a built payload,
    because this is asked on every ingest and bundling to answer it would put a
    build on the maintenance path.
    """
    if shape == SHAPE_WORKSPACE:
        return {"package.json"}
    from . import nodebundle

    return {nodebundle.ENTRY, *nodebundle.SIDECARS}


def _layout_is_stale(target: Path, shape: str) -> bool:
    """Does `.fux/node/` hold something other than what its shape declares?

    🔴 **The version is NOT a sufficient test, and this repository is the proof.**
    `ensure_node_reader` compared `package.json`'s version against the engine's,
    so a directory written by *this* version before the payload changed shape
    kept its 44-file module tree and the prune never ran — the version matched.
    A real consumer upgrading across a release is covered by the version; anyone
    tracking a single alpha from git is not, and neither was fux itself. Found by
    running the migration on this repo rather than by reading the code.

    A name-set comparison, never a byte comparison: the bytes are checked
    per-file when a write is actually happening.
    """
    if not target.is_dir():
        return True
    found = {
        p.relative_to(target).as_posix()
        for p in target.rglob("*")
        if p.is_file() and not p.relative_to(target).as_posix().startswith(_NODE_MODULES + "/")
    }
    return found != _expected_layout(shape)


def ensure_node_reader(root: Path, *, shape: "str | None" = None) -> "list[Path]":
    """Write `.fux/node/` in its declared shape and the `.fux/fux` shim.

    Returns every path written OR removed, which is what `fux setup` prints and
    what `ensure_layout`'s callers treat as "something changed".

    ⚠ **Overwrites only when the version, the shape, or the LAYOUT differs.**
    The layout test is what makes an in-place migration work at all — see
    `_layout_is_stale`, which exists because the version test alone left this
    repository's own `.fux/node/` holding 44 stale modules. Rewriting
    unconditionally would dirty the working tree on every ingest — this
    directory is COMMITTED, so a no-op ingest must produce a no-op diff. The
    shim is compared by bytes on every call for the same reason: it is three
    lines, and a stale one sends `fux` at a file that no longer exists.
    """
    from .. import __version__

    directory = fux_dir(root)
    current = node_shape(directory)
    declared = shape or current or SHAPE_VENDORED

    written: list[Path] = []
    target = directory / NODE_DIR
    if (
        node_version(directory) != __version__
        or current != declared
        or _layout_is_stale(target, declared)
    ):
        if declared == SHAPE_WORKSPACE:
            payload = [("package.json", _workspace_manifest(__version__))]
        else:
            payload = _packaged_node_files()

        for rel, data in payload:
            path = target / rel
            path.parent.mkdir(parents=True, exist_ok=True)
            if not path.exists() or path.read_bytes() != data:
                path.write_bytes(data)
                written.append(path)
        written.extend(_prune_node_reader(target, {rel for rel, _ in payload}))

    shim = directory / NODE_SHIM
    if not shim.exists() or shim.read_bytes() != _SHIM.encode("ascii"):
        shim.write_bytes(_SHIM.encode("ascii"))
        written.append(shim)
    if shim.exists():
        shim.chmod(_SHIM_MODE)
    return written


def derived_dir(root: Path, name: str) -> Path:
    """Return `.fux/<name>/`, created and tagged as a cache directory.

    For M2 to call when it materializes `runtime/` (M4's fetch cache nests
    inside it, at `runtime/fetch-cache/`, and does not call this directly).
    The tag is written once and never overwritten.
    """
    path = fux_dir(root) / name
    path.mkdir(parents=True, exist_ok=True)
    tag = path / "CACHEDIR.TAG"
    if not tag.exists():
        tag.write_bytes(CACHEDIR_TAG.encode("ascii"))
    return path
