"""The `.fux/` directory — one declared layout, committed vs derived.

Every child of `.fux/` is declared here as **committed** (belongs in git —
the index, the source lists, the consumer's fetcher) or **derived**
(rebuildable, gitignored, self-tagged). Nothing else should appear there;
`fux doctor` warns on anything undeclared, which is how a plane added by
accident gets noticed before it is committed.

Two rules make the split safe to live under a single dotdir:

- **`.fux/.gitignore` lists derived directory names explicitly, never `*`.**
  A blanket ignore plus an unignore is exactly how a committed plane goes
  missing silently; `fux doctor` asserts `git check-ignore` disagrees about
  `.fux/index`.
- **Derived directories carry `CACHEDIR.TAG`** ([the spec](https://bford.info/cachedir/)),
  so backup and archiving tools skip them without being told. Same pattern
  pytest uses for `.pytest_cache` (it writes `CACHEDIR.TAG` + `.gitignore` +
  `README.md` into its own cache dir) and mypy for `.mypy_cache`.

Consumer files are **write-if-missing, never overwritten**: `README.md` and
`.gitignore` may be annotated freely and fux will not clobber the edit. All
generated bytes are plain ASCII with explicit `\\n` — no wall-clock, no
locale, no console-encoding surprises on Windows.

See ADR-DOTFUX.
"""

from __future__ import annotations

from pathlib import Path

FUX_DIR = ".fux"

#: Declared children of `.fux/` — name -> one-line description for the README.
COMMITTED: dict[str, str] = {
    "index": "the wire-format index (ADR-RECORD)",
    "sources": "the committed source lists (`dirs`, `urls`), one entry per line",
    "fetchers": "consumer-owned code (`cdp.py`, `http.py`), edit freely",
    # ASCII only: `_readme()` encodes this table as ASCII on purpose, for
    # Windows consoles. An em-dash here fails the write, which is how this was
    # caught rather than shipped.
    "decoders": "consumer-owned code, one module per format. THESE COPIES ARE WHAT RUN, not the ones inside the installed package (ADR-DECODE)",
    "enrich": "pinned enrichment text, one file per source content sha, plus `queue.tsv` (W-86 P6: what fux could NOT read and a model must). Committed, because a backlog is a team fact",
}

#: Gitignored like DERIVED, and NOT rebuildable -- which is exactly why it is
#: not filed there. `runtime/` means "fux build can reconstruct this"; an
#: acquired blob can only be re-ACQUIRED, and only while the source still
#: exists and the session that reached it still holds (ADR-ACQUIRED).
ACQUIRED: dict[str, str] = {
    # ASCII only, like every other value in these tables.
    "acquired": "the bytes a fetch actually returned, for URLs whose line says keep=true. Gitignored and NOT rebuildable - re-acquirable only, and only while the source is still reachable; carries CACHEDIR.TAG",
}

DERIVED: dict[str, str] = {
    "runtime": "M2 accelerator segments, M4's fetch cache at `runtime/fetch-cache/`, the write lock, and `enrich-progress.tsv` (W-86 P6: which queued documents THIS machine has handled - local by design, so two people's progress cannot conflict on a pull)",
}

#: Files fux generates at the top level of `.fux/` (write-if-missing).
GENERATED_FILES = ("README.md", ".gitignore")

#: Committed FILES at the top level, as opposed to committed directories.
#:
#: **This tuple exists because its absence was a live defect.** `DECLARED` was
#: built from `COMMITTED` (directories), `DERIVED` and `GENERATED_FILES`, so a
#: committed *file* had no row anywhere and `fux doctor` reported it as an
#: undeclared entry — ADR-DOTFUX veto condition 1, firing. `tune.toml` would
#: have shipped into that warning on day one; `.fux/enrich/` was already in it.
#: Found 2026-08-24 by checking the claim instead of asserting it.
COMMITTED_FILES: dict[str, str] = {
    "tune.toml": "the tunables: HOW results are ordered, never what is indexed (ADR-TUNE)",
    "output.toml": "the output defaults: HOW a result is SHOWN, never which documents come back (ADR-OUTPUT)",
    # ASCII only, like every other value in these tables -- `_readme()` encodes
    # them for a Windows console.
    ".fuxignore": "what is NOT indexed, in .gitignore's grammar. The one place exclusions belong, read before the source lists (ADR-FUXIGNORE)",
    # ASCII only, like every other value in these tables.
    # ASCII only, like every other value in these tables.
    "pii.toml": "what is REDACTED from the committed index - and ONLY from it. The acquired bytes, the refer plane and every answer quote still see the document as it is (ADR-PII)",
    "refusals.toml": "what a REFUSAL looks like here - the sign-in walls, paywalls and error shells a server returns INSTEAD of the document. Consumer-owned; fux ships no vendor knowledge (ADR-REFUSAL)",
}

#: Everything legally found directly under `.fux/`; anything else is a warning.
DECLARED = (*COMMITTED, *COMMITTED_FILES, *DERIVED, *ACQUIRED, *GENERATED_FILES)

# CACHEDIR.TAG's first line is a fixed signature — byte-exact, per the spec.
CACHEDIR_SIGNATURE = "Signature: 8a477f597d28d172789f06886806bc55"
CACHEDIR_TAG = (
    f"{CACHEDIR_SIGNATURE}\n"
    "# This file is a cache directory tag created by fux.\n"
    "# For information about cache directory tags, see https://bford.info/cachedir/\n"
)

_GITIGNORE = (
    "# Gitignored planes, BY NAME. NEVER add `*` here: `.fux/index/`,\n"
    "# `.fux/sources/`, `.fux/fetchers/` and `.fux/decoders/` are committed,\n"
    "# and a blanket ignore would drop them from git silently. `fux doctor`\n"
    "# checks exactly that.\n"
    "#\n"
    "# `runtime/` is DERIVED: rebuildable from the committed index by\n"
    "# `fux build`. `acquired/` is not -- it holds the bytes a fetch actually\n"
    "# returned, which can only be re-acquired while the source is still\n"
    "# reachable. Both are ignored; only one can be regenerated.\n"
    + "".join(f"{name}/\n" for name in DERIVED)
    + "".join(f"{name}/\n" for name in ACQUIRED)
)


def _readme() -> str:
    # Plain ASCII on purpose: no em-dashes, no smart quotes. These bytes get
    # printed and diffed on Windows consoles whose codepage cannot encode them.
    rows = [
        "# `.fux/`",
        "",
        "Fux's directory in your repo. Every child is declared below, in one",
        "of THREE kinds:",
        "",
        "- **committed** - belongs in git. This is the product.",
        "- **derived** - rebuildable from the committed bytes by `fux build`.",
        "  Ignored, tagged with [`CACHEDIR.TAG`](https://bford.info/cachedir/),",
        "  and safe to delete at any time.",
        "- **acquired** - the bytes a fetch returned. Ignored and tagged like",
        "  derived, but NOT rebuildable: deleting it loses the only local copy,",
        "  and getting it back means re-fetching from a source that must still",
        "  exist and a session that must still hold.",
        "",
        "| entry | kind | what it is |",
        "|---|---|---|",
        "| `README.md` | committed | this file: written once by fux, yours to annotate |",
        "| `.gitignore` | committed | lists the ignored directories BY NAME, never `*` |",
    ]
    rows += [f"| `{name}/` | committed | {desc} |" for name, desc in COMMITTED.items()]
    rows += [f"| `{name}` | committed | {desc} |" for name, desc in COMMITTED_FILES.items()]
    rows += [f"| `{name}/` | derived | {desc}; carries `CACHEDIR.TAG` |" for name, desc in DERIVED.items()]
    rows += [f"| `{name}/` | acquired | {desc} |" for name, desc in ACQUIRED.items()]
    rows += [
        "",
        "## The fetchers are yours",
        "",
        "`fetchers/http.py` and `fetchers/cdp.py` are **your** code, committed",
        "to **your** repo. `fux setup` writes them once if they are missing;",
        "`fux ingest` never writes a fetcher at all. Fux loads one by path",
        "under `fux add <URL>` or `fux update`, and never rewrites it. Change the",
        "port, the transport, the extraction, anything.",
        "",
        "One consequence of living in a dotdir: linters that skip hidden",
        "directories by default (ruff does) will not lint it. That is fine, it",
        "is consumer code, not a CI target.",
        "",
        "## Rules",
        "",
        "- Anything here that is not in the table above is undeclared; `fux",
        "  doctor` warns about it.",
        "- Derived directories can be deleted at any time. Committed ones",
        "  cannot be rebuilt from anything but their source systems.",
        "- `acquired/` sits between the two: deleting it costs you the local",
        "  copy of bytes you already fetched, and a re-fetch is the only way",
        "  back. `fux doctor` reports its size.",
        "- Fux writes `README.md` and `.gitignore` **only if missing**. Your",
        "  edits survive every ingest.",
        "",
    ]
    return "\n".join(rows)


def fux_dir(root: Path) -> Path:
    return root / FUX_DIR


def ensure_layout(root: Path) -> list[Path]:
    """Create `.fux/` and its generated files if absent; return what was written.

    Idempotent and non-destructive: an existing `README.md`/`.gitignore` is
    left exactly as the consumer edited it.
    """
    directory = fux_dir(root)
    directory.mkdir(parents=True, exist_ok=True)
    written: list[Path] = []
    for name, text in (("README.md", _readme()), (".gitignore", _GITIGNORE)):
        path = directory / name
        if not path.exists():
            path.write_bytes(text.encode("ascii"))
            written.append(path)
    return written


def derived_dir(root: Path, name: str) -> Path:
    """Return `.fux/<name>/`, created and tagged as a cache directory.

    For M2 to call when it materializes `runtime/` (M4's fetch cache nests
    inside it, at `runtime/fetch-cache/`, and does not call this directly).
    The tag is written once and never overwritten.
    """
    path = fux_dir(root) / name
    path.mkdir(parents=True, exist_ok=True)
    tag = path / "CACHEDIR.TAG"
    if not tag.exists():
        tag.write_bytes(CACHEDIR_TAG.encode("ascii"))
    return path
