#!/usr/bin/env python3
"""Generate the golden ladder's `ext/` corpus — deterministic, prefix-stable.

W-136 phase 2. The sealed golden benchmark's seed documents live in the fux
repo at `work/golden/seed/`; this script produces everything *around* them, so
a rung of N documents is 20 seed documents plus the first N-20 documents of the
stream this file emits.

## The one property that matters: PREFIX STABILITY

The ladder is **nested** — rung 200's documents are rung 100's documents, byte
for byte, plus 100 more. That is what makes two rungs comparable at all. So
document `i` of the stream must be byte-identical whatever `--count` is asked
for, which is why every document draws from `random.Random(SEED + i)` and never
from one shared stream. Nothing here may depend on `n`.

## The block, and why it is ten

Documents are emitted in blocks of ten, and each block holds the category mix
`work/golden/README.md` asks for exactly:

    0 sibling   1 adjacent  2 filler   3 sibling   4 adjacent
    5 variant   6 sibling   7 adjacent 8 filler    9 sibling

    -> sibling 4 (40%) · adjacent 3 (30%) · filler 2 (20%) · variant 1 (10%)

Every rung's ext count is a multiple of ten (80 · 180 · 480 · 980), so every
rung gets that mix and no rung ever cuts a block in half.

**Slot 5 and slot 6 are a supersession pair.** Slot 5 is the retired document
and is written under `ext/archive/`; slot 6 is its successor and declares
`supersedes:` pointing at it. They are adjacent in the stream so that a rung
boundary can never admit a `supersedes:` line whose target is not in the rung.

## The rule this file is most able to break

🔴 **No generated document may state a fact about a seed entity.** Vocabulary
may overlap — that is the point of a hard negative — but no named company,
person, facility, vendor, room, truck, form or incident from `seed/` may
appear. `SEED_ENTITIES` is the blacklist and `check_corpus()` enforces it over
the emitted bytes; the generator fails rather than writes a corpus that would
silently change the answer key's truth.

## Authored documents come first

`golden-ext-authored/` holds hand-written hard negatives, emitted in filename
order before anything generated, so the hardest documents are in *every* rung.
Each document's `origin` (`authored` | `generated`) is recorded per line in the
rung manifest.

Usage:
    python3 make_golden_ext.py --out <rung-dir> --count 980
    python3 make_golden_ext.py --check          # blacklist + determinism self-test
"""

from __future__ import annotations

import argparse
import datetime as dt
import hashlib
import random
import re
import sys
from pathlib import Path

SEED = 20260912
HERE = Path(__file__).resolve().parent
AUTHORED_DIR = HERE / "golden-ext-authored"

# --------------------------------------------------------------------------
# The blacklist — every proper name the seed corpus owns.
# --------------------------------------------------------------------------
# Matched case-insensitively as whole words over the generated bytes. Drawn
# from a proper-noun sweep of all twenty seed documents, then widened by hand
# with the codes and multi-word names a token sweep splits apart.
SEED_ENTITIES = [
    # company, vendors, systems
    "quillfern", "tessaline", "kalpa", "dockwise", "bharatvac", "manjara",
    "compliance-red", "kfs-2014", "klp", "tsl", "kv-ngp", "qcl",
    "exception_csv_v2", "qa-shared",
    # places the seed corpus owns
    "nagpur", "ngp", "pune", "guwahati", "ghy", "coimbatore", "cbe",
    "temple street",
    # people
    "revathi", "iyer", "farhan", "qureshi", "bunty", "chauhan", "riniki",
    "bora", "venkatesan", "gregor", "lindqvist", "sandhu", "anjali",
    "deshmukh", "nalini", "patil", "saira", "reyes", "meera", "krishnan",
    "mahesh", "karim",
    # rooms, bays, trucks, forms, practices
    "q-3", "q-g2", "q-c1", "rf-118", "rf-221", "red sleeve", "holding lane b",
    "c2-red-sleeve", "g-cold-1", "g-dairy-2", "cbe-pharma", "cbe-frozen",
]

# --------------------------------------------------------------------------
# The fictional universe the ext corpus is built from. None of it is in seed/.
# --------------------------------------------------------------------------
COMPANIES = [
    ("Marrowbeck Chilled Freight Ltd.", "Marrowbeck", ["Bhopal", "Indore"], "MBK"),
    ("Vantorix Cold Storage LLP", "Vantorix", ["Surat", "Rajkot"], "VTX"),
    ("Halberd & Frost Perishables", "Halberd & Frost", ["Ludhiana", "Jalandhar"], "HFP"),
    ("Sundari Fresh Distribution", "Sundari Fresh", ["Kochi", "Tiruchirappalli"], "SFD"),
    ("Norvell Reefer Lines", "Norvell", ["Visakhapatnam", "Rajahmundry"], "NRL"),
    ("Petrichor Cold Chain Services", "Petrichor", ["Siliguri", "Jamshedpur"], "PCC"),
    ("Okapi Frozen Logistics", "Okapi", ["Mysuru", "Hubballi"], "OKF"),
    ("Braidwood Temperature Control", "Braidwood", ["Kanpur", "Prayagraj"], "BWD"),
    ("Zephyrine Agro Cold", "Zephyrine", ["Nashik", "Chhatrapati Sambhajinagar"], "ZAC"),
    ("Cindermoor Distribution", "Cindermoor", ["Raipur", "Bilaspur"], "CDM"),
]

TELEMATICS = [
    "Ostrelle Telematics", "Kavach Fleet IoT", "Brambleway Sensors",
    "Northgate Track", "Pallavi Telemetry", "Sixfold Cold Monitor",
]
SLOT_SYSTEMS = ["SlotHarbour", "DockPilot", "BayQueue", "GatewaySlots", "Loadwright"]

PEOPLE = [
    "Devika Ranganathan", "Imran Sheikh", "Poulomi Das", "Harsh Vaidya",
    "Tanmay Joshi", "Leela Nambiar", "Rustom Contractor", "Ayesha Kalra",
    "Vikram Sethi", "Nandita Roy", "Girish Pai", "Sneha Barve",
    "Abhijit Mukherjee", "Kavya Reddy", "Om Prakash Tiwari", "Fiona D'Souza",
    "Sanjot Bhamra", "Elango Subramani", "Ritika Chandola", "Bhaskar Naidu",
]

PRODUCTS = [
    ("vaccine", 2.0, 8.0), ("insulin", 2.0, 8.0), ("blood plasma", -30.0, -18.0),
    ("milk", 0.0, 4.0), ("paneer", 0.0, 5.0), ("curd", 0.0, 5.0),
    ("frozen seafood", -22.0, -18.0), ("ice cream", -25.0, -18.0),
    ("mango pulp", -20.0, -18.0), ("chilled poultry", -1.0, 2.0),
]

# Headings lifted from the seed documents' shapes on purpose: a sibling that
# matches on heading but carries other facts is the `heading` negative control
# W-142 needs, and the hardest negative the lexical plane will see.
SIBLING_KINDS = [
    ("sop", "md", "Temperature Excursion Response SOP"),
    ("thresholds", "yaml", "sensor threshold documentation"),
    ("postmortem", "md", "Post-incident review"),
    ("handover", "txt", "Night shift handover log"),
    ("decision", "md", "Telematics vendor decision"),
    ("thread", "eml", "Telematics cutover thread"),
    ("ratecard", "md", "Rate card and surcharges"),
    ("hours", "md", "Driver hours and safety policy"),
    ("dockwiki", "html", "Dock scheduling rules"),
    ("faq", "md", "New joiner FAQ"),
    ("notification", "md", "Customer notification matrix"),
    ("quarantine", "md", "Quarantine bay and disposition rules"),
]

ADJACENT_KINDS = [
    ("hr-leave", "md", "Leave and attendance policy"),
    ("it-access", "md", "System access and joiner-mover-leaver"),
    ("procurement", "md", "Procurement and vendor onboarding"),
    ("facilities", "md", "Facilities and ammonia plant maintenance"),
    ("finance-close", "md", "Month-end close checklist"),
    ("training", "txt", "Training calendar and attendance"),
    ("workshop", "md", "Fleet workshop and preventive maintenance"),
    ("security", "md", "Gate security and visitor procedure"),
    ("insurance", "eml", "Insurance claim correspondence"),
    ("onboarding", "html", "Customer onboarding wiki page"),
    ("payroll", "yaml", "payroll configuration notes"),
    ("travel", "md", "Travel and expense rules"),
]

FILLER_KINDS = [
    ("release-notes", "md", "Release notes"),
    ("municipal", "html", "Municipal ward notice"),
    ("bee", "md", "Beekeeping association minutes"),
    ("astronomy", "md", "Astronomy society observing report"),
    ("syllabus", "md", "Course syllabus"),
    ("recipes", "md", "Community recipe collection"),
    ("bicycle", "txt", "Bicycle workshop service notes"),
    ("museum", "html", "Museum catalogue entry"),
    ("chess", "md", "Chess club bulletin"),
    ("weather", "yaml", "station configuration"),
    ("library", "md", "Library acquisition list"),
    ("orchestra", "txt", "Rehearsal schedule"),
]

BLOCK = ["sibling", "adjacent", "filler", "sibling", "adjacent",
         "variant", "sibling", "adjacent", "filler", "sibling"]

# Only these sibling kinds render YAML frontmatter, and `supersedes:` is a
# frontmatter key — so both halves of a supersession pair are drawn from HERE
# and nowhere else. Drawing from the full list silently produced superseders
# whose `supersedes:` line was dropped by the template that rendered them, and
# `check_corpus` could not see it because the *targets* that remained all
# existed. `--check` now counts pairs, which is what catches this.
SUPERSEDABLE = [k for k in SIBLING_KINDS
                if k[0] in ("sop", "postmortem", "decision", "ratecard",
                            "hours", "notification", "quarantine")]


# --------------------------------------------------------------------------
# helpers
# --------------------------------------------------------------------------
def rng_for(i: int) -> random.Random:
    """Per-document RNG. Depends on the index and nothing else — that is what
    keeps document `i` byte-identical for every `--count`."""
    return random.Random(SEED + i * 7919)


def a_date(r: random.Random, lo: int, hi: int) -> str:
    start = dt.date(lo, 1, 1)
    end = dt.date(hi, 12, 28)
    return (start + dt.timedelta(days=r.randrange((end - start).days))).isoformat()


def pick_company(r: random.Random):
    return r.choice(COMPANIES)


def slug(s: str) -> str:
    return re.sub(r"[^a-z0-9]+", "-", s.lower()).strip("-")


# --------------------------------------------------------------------------
# Document bodies. Each returns the full file text.
# --------------------------------------------------------------------------
def sibling_doc(i: int, r: random.Random, kind, supersedes: str | None = None) -> str:
    key, ext, title = kind
    full, short, cities, code = pick_company(r)
    city = r.choice(cities)
    person = r.choice(PEOPLE)
    person2 = r.choice([p for p in PEOPLE if p != person])
    vendor = r.choice(TELEMATICS)
    slots = r.choice(SLOT_SYSTEMS)
    prod, lo, hi = r.choice(PRODUCTS)
    mins = r.choice([10, 12, 15, 18, 20, 25, 30, 45])
    mins2 = r.choice([5, 8, 10, 20, 40])
    year = r.randrange(2022, 2027)
    bay = f"{code}-Q{r.randrange(1, 9)}"
    room = f"{code}-{r.choice('ABCDEFG')}{r.randrange(1, 6)}"
    truck = f"{code}-{r.randrange(100, 999)}"
    fm_sup = f"supersedes: {supersedes}\n" if supersedes else ""

    if key == "sop" or (ext == "md" and key in ("quarantine",)):
        return f"""---
title: {title} — {short}
doc_id: {code}-QA-{r.randrange(10, 99)}
owner: {person}
department: Quality
status: in_force
effective_date: {year}-{r.randrange(1,13):02d}-{r.randrange(1,28):02d}
{fm_sup}---

# {title}

## 1. Purpose

1.1. This procedure defines how {full} responds to a suspected or confirmed
temperature excursion in its cold rooms, docks, cross-dock lanes and reefer
bodies at the {city} site. It applies to {prod} and to any customer stock moved
under a written temperature commitment.

1.2. An excursion means a recorded temperature outside the allowed band for
longer than the allowed duration. One hand-held reading does not release stock.

## 2. Products and limits

2.1. {prod.capitalize()} must remain between {lo:+.1f} C and {hi:+.1f} C. A high
excursion is declared when an approved sensor records more than {hi:+.1f} C for
{mins} continuous minutes.

2.2. A low excursion is declared below {lo:+.1f} C for {mins2} continuous
minutes. Staging time on a covered dock counts towards both.

2.3. Room {room} is the {prod} room at {city}. Quarantine bay {bay} receives any
stock placed on hold.

## 3. Approved records

3.1. {vendor} is the first electronic source for temperature history at {full}.
Independent loggers and calibrated probes support an investigation but do not
overrule it unless Quality documents a sensor failure.

3.2. Hand-written dock readings are acceptable only for the first containment
decision and must be replaced by a downloaded record before release or billing.

## 4. Immediate containment

4.1. Stop movement of the affected pallet, crate, reefer body or room bay.

4.2. Photograph the sensor display, seal number, dock clock and pallet labels
before anyone debates disposition. Truck {truck} carries a spare logger bin.

4.3. Do not warm, chill, ventilate or shield the probe to make a display look
normal.

## 5. Notifications

5.1. Patient-critical stock: notify the customer within {r.choice([1,2,3,4])}
hours of a confirmed excursion. {person2} holds the escalation list.

5.2. Food customers are told by the next scheduled check-in unless spoilage is
visible or odour is present.

## 6. Closure

6.1. Quality closes the investigation and records one of release, conditional
release, hold, or destroy. Finance records value only afterwards.

6.2. The case file is kept for {r.choice([3,5,7])} years.
"""

    if ext == "yaml":
        return f"""# {short} legacy sensor threshold documentation
# Author: {person}
# Later edit: {person2}, {year}-{r.randrange(1,13):02d}-{r.randrange(1,28):02d}
# Documentation only; {vendor} is configured elsewhere.
schema_version: "{r.randrange(0,2)}.{r.randrange(1,9)}"
document_status: "legacy-doc"
company: "{full}"
sample_every_seconds: {r.choice([30, 60, 120, 300])}
default_alarm_repeat_minutes: {r.choice([5, 10, 15, 20])}

contacts:
  quality_ext: {r.randrange(200, 900)}
  fleet_control_ext: {r.randrange(200, 900)}
  escalation_group: "{short.split()[0]}-Escalation"

facilities:
  {slug(city).replace('-', '_')}_dc:
    aliases:
      - "{city} DC"
      - "{code} hub"
    rooms:
      {room}:
        product: "{prod.replace(' ', '_')}"
        unit: "C"
        low_celsius: {lo:.1f}
        low_minutes: {mins2}
        high_celsius: {hi:.1f}
        high_minutes: {mins}
        quarantine_bay: "{bay}"

truck_profiles:
  owned_reefer:
    unit: "C"
    logger_poll_seconds: {r.choice([30, 60, 120])}
    door_open_warn_seconds: {r.choice([120, 180, 240])}
    allowed_manual_ack: {str(r.choice([True, False])).lower()}

notes:
  - "Keep the original sensor in place when adding a spare logger."
  - "This file records old values because auditors ask how the previous vendor was configured."
"""

    if ext == "txt":
        return f"""{city.upper()} NIGHT SHIFT HANDOVER — {full}
Shift lead: {person}
Date: {year}-{r.randrange(1,13):02d}-{r.randrange(1,28):02d}

22:{r.randrange(10,59)} Gate handover taken. {r.randrange(3,14)} reefers on yard.
23:{r.randrange(10,59)} Room {room} alarm, {prod} at {hi + r.random()*2:+.1f} C.
      Called {person2}. Spare logger placed, original sensor left in place.
00:{r.randrange(10,59)} Alarm cleared after {mins2} min. Quality informed, no
      excursion declared because the duration stayed under {mins} minutes.
01:{r.randrange(10,59)} Truck {truck} reported a door-open event on the {city}
      bypass. Driver parked at a lit fuel plaza and kept the engine running.
02:{r.randrange(10,59)} Quarantine bay {bay} checked. Two pallets still on hold
      from the previous shift, paperwork with Quality.
04:{r.randrange(10,59)} {vendor} tablet in the guard cabin went offline. Wrote
      readings by hand in the register. IT ticket raised.
05:{r.randrange(10,59)} Handover to day shift. Nothing outstanding except the
      tablet and the two held pallets.

NOTE: do not troubleshoot a telematics device while driving. Park first.
"""

    if ext == "eml":
        dom = slug(short.split()[0])
        return f"""From: {person} <{slug(person)}@{dom}.example>
To: {person2} <{slug(person2)}@{dom}.example>
Cc: quality@{dom}.example
Subject: Re: Fw: {title} — {city} cutover
Date: {year}-{r.randrange(1,13):02d}-{r.randrange(1,28):02d} {r.randrange(9,18)}:{r.randrange(10,59)}

Confirming what we agreed on the call.

1. {vendor} goes live for {city} on the first of next month. Every trip opened
   after that date is in {vendor}; nothing new goes into the old system.
2. Historic trips stay where they are. Quality pulls them from the old export
   for audits, and we are not migrating them.
3. Polling moves to {r.choice([30, 60, 120])} seconds. The old {r.choice([5, 10])}-minute
   polling is why our timelines needed interpolation.

> -----Original Message-----
> From: {person2}
> Subject: Fw: {title} — {city} cutover
>
> Finance has signed the PO. Total {r.randrange(9, 40)}.{r.randrange(10,99)} lakh
> for migration, devices and API onboarding, then Rs. {r.randrange(600, 1400)}
> per active truck per month.
>
> One open point: the customer annexes quote screenshots from the old app. Who
> reissues those? We cannot send an audit packet that shows a dead vendor.

{person}
{full}
"""

    if ext == "html":
        return f"""<!doctype html>
<html>
<head>
  <title>{short} Wiki - {title}</title>
  <meta name="exported" content="old-wiki-html">
</head>
<body>
<div id="nav">Home | {city} Hub | Dock calendar | Edit this page</div>
<h1>{title}</h1>
<p class="notice">Exported from the {short} wiki. Some links may be stale.</p>
<p>Last real review: {year}-{r.randrange(1,13):02d}-{r.randrange(1,28):02d}. Do not treat the wiki as a temperature SOP.</p>

<h2>{city} DC</h2>
<p>Book {city} slots in {slots} before {r.randrange(14,19)}:00 on the previous day.
Pharma uses dock {r.randrange(1,8)}, dairy uses docks {r.randrange(1,4)} and {r.randrange(4,7)},
and frozen food uses dock {r.randrange(1,8)}.</p>
<p>No unloading is planned between {r.randrange(11,15)}:{r.choice(['00','10','20','30','40'])}
and {r.randrange(11,15)}:{r.choice(['00','15','30','45'])} because the ammonia plant runs its defrost check.</p>

<h2>Customer class grace table</h2>
<table>
<tr><th>class</th><th>grace</th><th>penalty note</th></tr>
<tr><td>pharma critical</td><td>{r.choice([10,15,20,25])} min</td><td>call Quality and the shift lead</td></tr>
<tr><td>dairy</td><td>{r.choice([10,15,20,25])} min</td><td>after-hours wait may apply</td></tr>
<tr><td>frozen</td><td>{r.choice([5,10,15])} min</td><td>protect freezer order</td></tr>
<tr><td>dry grocery</td><td>{r.choice([25,30,45])} min</td><td>not cold chain</td></tr>
</table>

<h2>Late arrivals</h2>
<p>A late arrival goes to the {r.choice(['north','south','east','west'])} holding
lane and the shift lead is called. Booking is not cancelled automatically.</p>

<div id="footer">Last edited by {person}. Page id: WIKI-{code}-{r.randrange(10,99)}.</div>
</body>
</html>
"""

    # remaining md kinds: postmortem / decision / ratecard / hours / faq / notification
    if key == "postmortem":
        return f"""---
title: Post-incident review — {city} {prod} excursion
owner: {person}
status: closed
effective_date: {year}-{r.randrange(1,13):02d}-{r.randrange(1,28):02d}
{fm_sup}---

# Post-incident review — {city} {prod} excursion

## Summary

On the night in question, room {room} at the {full} {city} site held {prod}
above {hi:+.1f} C for {mins + r.randrange(5, 40)} continuous minutes. The stock
was placed in quarantine bay {bay} and released only after the customer
returned a stability letter.

## Timeline

| time | event |
|---|---|
| 21:{r.randrange(10,59)} | {vendor} raises a high-temperature alarm on {room} |
| 21:{r.randrange(10,59)} | Alarm acknowledged in the app; containment not started |
| 22:{r.randrange(10,59)} | Shift lead {person2} attends and stops movement |
| 23:{r.randrange(10,59)} | Stock moved to {bay}; photographs taken |
| 06:{r.randrange(10,59)} | Quality opens the investigation record |

## What went wrong

1. **Acknowledging is not containing.** The alarm was acknowledged eleven
   minutes before anyone walked to the room. Acknowledgement silences the app;
   it does nothing to the product.
2. The ammonia plant defrost overlapped the door-open window, so the room had
   no recovery headroom.
3. The spare logger bin was empty, so the second reading came from a hand-held
   probe that the procedure does not accept for release.

## Actions

| action | owner | due |
|---|---|---|
| Re-stock every spare logger bin at {city} | {person2} | {year}-{r.randrange(1,13):02d}-15 |
| Separate the defrost window from the loading window | {person} | {year}-{r.randrange(1,13):02d}-28 |
| Make acknowledgement require a containment checkbox | IT service desk | next release |
"""

    if key == "decision":
        return f"""---
title: Telematics vendor decision — {short} {year}
status: accepted
owner: {person}
effective_date: {year}-{r.randrange(1,13):02d}-{r.randrange(1,28):02d}
{fm_sup}---

# Telematics vendor decision — {short} {year}

## Context

{full} runs {r.randrange(40, 260)} owned reefers, {r.randrange(10, 90)} hired
devices during peak months and {r.randrange(15, 70)} fixed sensors across rooms
and docks at {city} and its satellite sites. The current contract expires this
December.

## Decision

{full} will move to {vendor} for {r.choice([24, 36, 48])} months. The migration
and onboarding charge is Rs. {r.randrange(8, 40)}.{r.randrange(10,99)} lakh. The
recurring charge is Rs. {r.randrange(600, 1500)} per active truck per month and
Rs. {r.randrange(180, 450)} per fixed sensor per month.

No split-vendor model will be used. One support desk, one monthly export.

## Reasons

- {vendor} polls every {r.choice([30, 60, 120])} seconds; the incumbent polls
  every {r.choice([5, 10])} minutes, which is why timelines need interpolation.
- Local service staff are within the {city} municipal limits and have replaced
  failed devices inside one working day during the trial.
- The API export can be pulled by Quality without a support ticket.

## Consequences

- Customer annexes that quote screenshots of the old app must be reissued.
- Historic trips are **not** migrated. Audit packets before the cutover come
  from the old export, and Quality keeps a copy of the export script.
- Review no earlier than {year + 2} unless three major alert failures occur in
  one quarter.
"""

    if key == "ratecard":
        return f"""---
title: Rate card and surcharges — {short} {year}
owner: {person}
department: Finance
status: in_force
effective_from: {year}-{r.randrange(1,13):02d}-01
{fm_sup}---

# Rate card and surcharges — {short} {year}

Applies to standard quotations unless a signed annex says otherwise.

## Base rates

| service | rate | unit |
|---|---:|---|
| {prod.capitalize()}, {cities[0]} to {cities[1]} lane | Rs. {r.randrange(12, 40)}.{r.randrange(10,99)} | per kg |
| Dairy crates inside {city} city | Rs. {r.randrange(2, 6)}.{r.randrange(10,99)} | per crate |
| Frozen intercity pallet | Rs. {r.randrange(1500, 3200)} | per pallet |
| Emergency dry-ice packing | Rs. {r.randrange(30, 70)} | per kg |
| Passive shipper hire | Rs. {r.randrange(700, 1600)} | per shipper per trip |

## Surcharges

| item | rule |
|---|---|
| Diesel surcharge | {r.randrange(4, 9)}.{r.choice(['00','25','50','75'])}% when HSD exceeds Rs. {r.randrange(84, 99)}/litre |
| After-hours dock wait | first {r.choice([30, 45, 60])} minutes free, then Rs. {r.randrange(400, 900)}/hour |
| Audit packet | included for patient-critical stock |
| Monsoon rain-cover handling | Rs. {r.randrange(150, 400)} per trip, June to September |

GST at 18% is charged on freight, surcharge and wait time unless the customer
holds a written exemption letter.
"""

    if key == "hours":
        return f"""---
title: Driver hours and safety policy — {short}
doc_id: {code}-HSE-{r.randrange(10,99)}
owner: {person}
status: in_force
effective_date: {year}-{r.randrange(1,13):02d}-{r.randrange(1,28):02d}
{fm_sup}---

# Driver hours and safety policy — {short}

## 1. Daily limits

1.1. A driver may drive at most {r.choice([8, 9, 10])} hours in any period of
24 hours, extended to {r.choice([10, 11, 12])} hours no more than twice a week.

1.2. A break of at least {r.choice([30, 40, 45])} minutes is taken after
{r.choice([4, 4.5, 5])} hours of driving. The break is not taken at a dock while
waiting for a slot.

## 2. Rest

2.1. Daily rest is {r.choice([9, 10, 11])} continuous hours. Weekly rest is
{r.choice([36, 45, 48])} hours.

2.2. Sleeping in a running reefer cab is permitted only at a lit plaza with the
handbrake engaged and the doors locked.

## 3. Exceptions

3.1. The limits may be exceeded only to reach a safe stopping place, and the
reason is written on the trip sheet the same day.

3.2. A slot that cannot be met inside the driver's remaining hours is
**rebooked, not driven to**. A manager who instructs otherwise is reported to
Fleet Control, who record the instruction.

## 4. Mobile phones, alcohol and seat belts

4.1. No hand-held device while the vehicle is moving, telematics included.

4.2. Zero alcohol. A positive test ends the shift immediately.

4.3. Seat belts are worn by every occupant including yard moves.
"""

    if key == "notification":
        return f"""---
title: Customer notification matrix — {short} {year}
owner: {person}
status: in_force
effective_date: {year}-{r.randrange(1,13):02d}-{r.randrange(1,28):02d}
{fm_sup}---

# Customer notification matrix — {short} {year}

## Who is told, and how fast

| customer class | trigger | notify within | channel |
|---|---|---:|---|
| patient critical | confirmed excursion | {r.choice([1,2,3])} h | phone then written |
| patient critical | suspected, unconfirmed | {r.choice([4,6,8])} h | written |
| dairy | visible spoilage or odour | {r.choice([2,4,6])} h | phone |
| dairy | confirmed excursion, no spoilage | next check-in | written |
| frozen restaurant chain | confirmed excursion | end of business day | phone then written |
| dry grocery | any | next working day | written |

## Wording

The first notice says *"temperature excursion under investigation"* and nothing
more. Nobody promises release, replacement credit or insurance recovery before
Quality records a disposition.

## Who signs

{person} signs patient-critical notices. {person2} signs everything else. A
notice is never sent by the shift that found the event without a signature.

## Escalation inside {full}

Quality, the site manager, Fleet Control when a vehicle is involved, and Finance
when stock is likely to be destroyed.
"""

    # faq
    return f"""# New joiner FAQ — {short}

The friendly version, not the legal one. If this page and the procedure
disagree, believe the procedure.

## What is the {code} hub?

{code} hub is the {city} DC. Both names turn up on challans and old wiki pages.

## Who do I call for a temperature alarm?

In the day, the Quality desk on extension {r.randrange(200,900)}. At night, the
shift lead first, then Fleet Control if a truck is moving. For patient-critical
stock the escalation group is {short.split()[0]}-Escalation.

## Which telematics app do we use?

{vendor}. Older training screenshots still show the previous vendor and the
guard-cabin tablet may still have it for audit lookups.

## What is {slots}?

{slots} is the slot calendar. Book before the cut-off on the previous day; a
late arrival goes to the holding lane and the shift lead is called.

## Common shorthand

{room} is a cold room, {bay} is a quarantine bay, and {code}-numbers are reefer
trucks. HSD means diesel for surcharge notes. If you do not know an acronym,
ask; pretending is how audit findings are born.
"""


def adjacent_doc(i: int, r: random.Random, kind) -> str:
    key, ext, title = kind
    full, short, cities, code = pick_company(r)
    city = r.choice(cities)
    person = r.choice(PEOPLE)
    person2 = r.choice([p for p in PEOPLE if p != person])
    year = r.randrange(2022, 2027)

    if ext == "yaml":
        return f"""# {short} {title}
# Owner: {person}
schema_version: "1.{r.randrange(0,9)}"
company: "{full}"
pay_cycle: "monthly"
cut_off_day: {r.randrange(20, 28)}
components:
  basic_percent: {r.randrange(40, 60)}
  hra_percent: {r.randrange(20, 40)}
  night_allowance_inr: {r.randrange(150, 600)}
  cold_room_allowance_inr: {r.randrange(200, 800)}
deductions:
  pf_percent: 12
  professional_tax_inr: {r.randrange(150, 250)}
notes:
  - "Night allowance applies to shifts starting after 21:00."
  - "Cold room allowance needs a signed medical fitness certificate on file."
"""

    if ext == "txt":
        return f"""{short.upper()} — {title.upper()}
Coordinator: {person}
Quarter: Q{r.randrange(1,5)} {year}

Week 1  Induction for new joiners — {r.randrange(6, 30)} seats — {city}
Week 2  Forklift refresher — {r.randrange(4, 18)} seats — {city}
Week 3  Ammonia awareness (mandatory, annual) — all site staff
Week 4  Defensive driving — hired-truck staff only

Attendance is marked on the register at the door, not in the chat group.
Anyone who misses a mandatory session is rescheduled inside thirty days;
{person2} tracks the list and escalates after two misses.

Trainers are booked one quarter ahead. A cancellation inside seven days is
charged to the requesting department.
"""

    if ext == "eml":
        dom = slug(short.split()[0])
        return f"""From: {person} <{slug(person)}@{dom}.example>
To: claims@{r.choice(['harborline','sentinel','ashgrove'])}-insure.example
Cc: {person2} <{slug(person2)}@{dom}.example>
Subject: {title} — claim {code}/{year}/{r.randrange(100, 999)}
Date: {year}-{r.randrange(1,13):02d}-{r.randrange(1,28):02d} {r.randrange(9,18)}:{r.randrange(10,59)}

Please find the documents for the above claim.

1. Delivery challan and weighbridge slip
2. Photographs of the seal and the pallet labels
3. The disposition record signed by Quality
4. Invoice value and the customer's written acceptance

The surveyor asked whether the vehicle was under {full} dispatch at the time.
It was — the hire agreement runs to the end of the season and the driver was on
our trip sheet.

We have not received the policy endorsement for the two vehicles added in
{r.choice(['March','April','May','June'])}. Could you confirm cover applies from
the date of addition and not from the date of endorsement?

{person}
{full}
"""

    if ext == "html":
        return f"""<!doctype html>
<html><head><title>{short} Wiki - {title}</title></head>
<body>
<h1>{title}</h1>
<p>Owner: {person}. Reviewed {year}.</p>
<h2>Before the first load</h2>
<ol>
<li>Signed service agreement and the temperature annex</li>
<li>Credit check cleared by Finance</li>
<li>Site contact list, including an out-of-hours number</li>
<li>Agreed notification classes and the escalation matrix</li>
</ol>
<h2>Systems</h2>
<p>Create the customer in the billing system first; the slot calendar reads the
code from there. A customer created only in the calendar will book slots that
nobody can invoice.</p>
<h2>Handover</h2>
<p>The sales owner hands over to {person2} at the first delivery, not at
signature. Anything agreed verbally before that is written into the annex or it
does not exist.</p>
</body></html>
"""

    bodies = {
        "hr-leave": f"""## Entitlement

Earned leave accrues at {r.randrange(15, 25)} days a year and may be carried
over to a maximum of {r.randrange(20, 45)} days. Casual leave is
{r.randrange(6, 12)} days and does not carry over.

## Applying

Apply {r.randrange(3, 15)} days ahead for anything longer than two days. Shift
staff apply through the roster, not by message, because the roster is what the
site manager reads at handover.

## Unplanned absence

Call the shift lead before the shift starts. An absence reported after the
shift has started is unplanned and is reviewed after the third occurrence in a
quarter.""",
        "it-access": f"""## Joiner

Access is requested by the hiring manager and approved by {person2}. Nobody
gets an account on a verbal request, including on the first day of peak season.

## Mover

A role change removes every old entitlement before adding the new one. This is
the step that is skipped, and it is why the last access review found
{r.randrange(9, 60)} accounts with warehouse rights nobody could explain.

## Leaver

Accounts are disabled on the last working day, not at the end of the notice
period. Shared guard-cabin tablets are re-paired the same week.""",
        "procurement": f"""## Thresholds

Below Rs. {r.randrange(20, 80)},000 a single quotation is enough. Above it,
three quotations or a written single-source justification.

## Vendor onboarding

A vendor is onboarded before the first purchase order, never after. Bank
details are confirmed by a call to a number taken from the signed agreement,
not from the invoice.

## Annual review

{person} reviews every recurring vendor each year for price, incident count and
whether the service is still needed.""",
        "facilities": f"""## Ammonia plant

The daily defrost check runs at the same time every day and is not moved to
suit a dock booking. If the two collide, the booking moves.

## Preventive maintenance

| asset | interval | owner |
|---|---|---|
| Condensers | monthly | {person} |
| Dock levellers | quarterly | {person2} |
| Emergency lighting | half-yearly | {person} |
| Ammonia detectors | annual, external | {person2} |

## Permits

Hot work, confined space and work at height each need a permit signed before
the work starts. A permit signed afterwards is an incident, not a permit.""",
        "finance-close": f"""## Day 1 to 3

Cut off goods received, accrue for trips delivered but not invoiced, and close
the fuel card statement.

## Day 4 to 6

Reconcile the reefer fuel and the toll accounts. Post the diesel surcharge
recovery and check it against the published rate card.

## Day 7

Management pack to {person2}. Anything unreconciled above Rs.
{r.randrange(10, 90)},000 is listed by name, not netted off.""",
        "workshop": f"""## Preventive schedule

| item | interval |
|---|---|
| Reefer unit service | {r.randrange(400, 1200)} running hours |
| Brake inspection | {r.randrange(8, 16)} weeks |
| Tyre rotation | {r.randrange(10, 30)},000 km |
| Door seal check | monthly |

## Breakdowns

A unit that fails twice in one quarter is taken off patient-critical work until
the root cause is closed. {person} keeps that list and it is not negotiable at
the dock.

## Parts

Genuine parts for the reefer unit; the warranty is void otherwise and the
saving is smaller than one rejected load.""",
        "security": f"""## Gate

Every vehicle is logged in and out with the seal number. A seal that does not
match the dispatch note stops the vehicle at the gate.

## Visitors

Visitors sign in, wear a badge and are escorted inside cold rooms. Auditors are
visitors.

## CCTV

Retained {r.randrange(20, 95)} days. A retrieval request goes to {person2} in
writing with the date, gate and time window.""",
        "travel": f"""## Booking

Book at least {r.randrange(5, 21)} days ahead where the trip is known. Late
booking needs a line of explanation, not an apology.

## Limits

| city class | room per night | meals per day |
|---|---:|---:|
| metro | Rs. {r.randrange(3500, 7000)} | Rs. {r.randrange(700, 1400)} |
| other | Rs. {r.randrange(2000, 4000)} | Rs. {r.randrange(500, 900)} |

## Claims

Claim within {r.randrange(15, 45)} days with receipts. {person} approves up to
the limits; anything above goes to Finance with the reason.""",
    }
    body = bodies.get(key, "## Scope\n\nThis document is maintained by the owner named above.")
    return f"""---
title: {title} — {short}
owner: {person}
department: {r.choice(['HR', 'IT', 'Finance', 'Facilities', 'Operations'])}
status: in_force
effective_date: {year}-{r.randrange(1,13):02d}-{r.randrange(1,28):02d}
---

# {title} — {short}

{body}
"""


def filler_doc(i: int, r: random.Random, kind) -> str:
    key, ext, title = kind
    person = r.choice(PEOPLE)
    year = r.randrange(2021, 2027)

    if ext == "yaml":
        return f"""# Amateur weather station configuration
station_id: "{r.choice('NSEW')}{r.randrange(100,999)}"
owner: "{person}"
elevation_m: {r.randrange(5, 900)}
sample_every_seconds: {r.choice([60, 300, 600])}
sensors:
  thermometer:
    model: "bead-{r.randrange(10,99)}"
    resolution_c: 0.1
    calibration_due: "{year}-{r.randrange(1,13):02d}-01"
  anemometer:
    model: "cup-{r.randrange(10,99)}"
    start_speed_ms: {r.randrange(1,4)}.{r.randrange(0,9)}
  rain_gauge:
    tip_mm: 0.2
uploads:
  interval_minutes: {r.choice([5, 10, 15])}
  retry_on_failure: true
notes:
  - "The screen was repainted in {year}; readings before that ran warm on still afternoons."
  - "Battery lasts one winter on the current logger."
"""

    if ext == "txt":
        if key == "bicycle":
            return f"""{title.upper()} — bench notes
Mechanic: {person}

{year}-{r.randrange(1,13):02d}-{r.randrange(1,28):02d}
  Touring frame, {r.randrange(1980, 2020)}. Rear hub had play; re-cupped and
  re-greased. Freehub body replaced. Chain at {r.randrange(50,90)}% wear, left.

{year}-{r.randrange(1,13):02d}-{r.randrange(1,28):02d}
  Hydraulic brakes bled, both ends. Pads glazed — sanded, advised replacement.
  Bottom bracket creak traced to the seatpost, not the BB. It usually is.

{year}-{r.randrange(1,13):02d}-{r.randrange(1,28):02d}
  Wheel build: 32h three-cross, {r.randrange(1000, 1400)} mm spokes, tension
  within 15% across the rear drive side. Trued to 0.2 mm.

Standing note: we do not fit a new chain to a worn cassette and call it a
service. Tell the customer the true price or refuse the job.
"""
        return f"""{title.upper()}
Season {year}-{year+1}
Convenor: {person}

Tuesdays 19:00  Full orchestra — main hall
Thursdays 18:30 Strings only — room {r.randrange(2,9)}
Saturdays 10:00 Sectional rehearsals, rotating

Concert dates: {r.randrange(1,28)} {r.choice(['March','April','May'])} and
{r.randrange(1,28)} {r.choice(['October','November'])}.

Please arrive tuned. Parts are in the pigeonholes, not in the inbox. Anyone
borrowing a stand light returns it the same evening; we have lost four.
"""

    if ext == "html":
        if key == "municipal":
            return f"""<!doctype html>
<html><head><title>Ward notice</title></head>
<body>
<h1>Ward {r.randrange(1, 60)} — public notice</h1>
<p>Issued {year}-{r.randrange(1,13):02d}-{r.randrange(1,28):02d}</p>
<h2>Water supply</h2>
<p>Supply will be interrupted between {r.randrange(9,12)}:00 and
{r.randrange(13,18)}:00 on {r.randrange(1,28)} {r.choice(['January','February','March','August'])}
for pipeline work near the junction. Storage is advised.</p>
<h2>Solid waste</h2>
<p>Wet and dry waste are collected on alternate days. Bulk garden waste is
collected on the first Saturday of the month from the collection point only.</p>
<h2>Objections</h2>
<p>Written objections to the draft development plan are received at the ward
office for {r.randrange(15, 45)} days from the date of this notice.</p>
</body></html>
"""
        return f"""<!doctype html>
<html><head><title>Catalogue entry</title></head>
<body>
<h1>Accession {r.randrange(1900, 2020)}.{r.randrange(100, 999)}</h1>
<p><strong>Object:</strong> {r.choice(['bronze lamp', 'palm-leaf manuscript', 'brass astrolabe', 'terracotta seal', 'wooden printing block'])}</p>
<p><strong>Period:</strong> {r.choice(['12th', '15th', '17th', '19th'])} century</p>
<p><strong>Acquired:</strong> {year - r.randrange(5, 60)}, by bequest</p>
<h2>Description</h2>
<p>Complete but for a small loss at the rim. Surface stable; earlier wax coating
removed during conservation in {year - r.randrange(1, 20)}.</p>
<h2>Display history</h2>
<p>Gallery {r.randrange(1, 12)} since {year - r.randrange(1, 15)}. Previously in
store; light levels restricted to {r.randrange(50, 200)} lux.</p>
</body></html>
"""

    bodies = {
        "release-notes": f"""## {r.randrange(1,9)}.{r.randrange(0,20)}.{r.randrange(0,9)} — {year}-{r.randrange(1,13):02d}-{r.randrange(1,28):02d}

### Added
- Keyboard navigation for the results list.
- An offline cache so the last query survives a reload.

### Fixed
- A crash when the filter box was emptied while a request was in flight.
- Dates rendered in the server's timezone rather than the reader's.

### Changed
- The export is now streamed; very large exports no longer hold memory.

### Deprecated
- The v1 endpoint. It keeps working for two more releases and then stops.""",
        "bee": f"""## Minutes

Present: {r.randrange(6, 22)} members. Apologies from four.

### Winter losses

Losses across the association ran at {r.randrange(8, 30)}% this winter, which is
about average. Two members reported isolation starvation in colonies that had
stores but not where the cluster was.

### Apiary

The site fence needs replacing before the swarm season. {person} has a quote and
will circulate it.

### Next meeting

Talk on queen rearing, then the honey show rules for this year.""",
        "astronomy": f"""## Session report

Site: rural, Bortle {r.randrange(3, 6)}. Seeing average, transparency good after
midnight.

### Observed

| object | instrument | note |
|---|---|---|
| Open cluster | {r.randrange(6, 12)}" reflector | Resolved to the core at 120x |
| Planetary nebula | same | Filter helped considerably |
| Double star | {r.randrange(60, 130)} mm refractor | Split cleanly at 180x |

### Notes

Dew was the limiting factor, not the sky. The heater strip died an hour in and
the rest of the session was spent fighting the corrector plate.""",
        "syllabus": f"""## Aims

To introduce the principles of the subject and the habits of reading that go
with it.

## Schedule

| week | topic | reading |
|---|---|---|
| 1–2 | Foundations | Chapters 1–3 |
| 3–5 | Core methods | Chapters 4–8 |
| 6 | Reading week | — |
| 7–9 | Applications | Selected papers |
| 10–12 | Project work | — |

## Assessment

Coursework {r.randrange(30, 60)}%, examination the remainder. Late work loses
{r.randrange(5, 15)}% a day unless an extension is agreed in advance.""",
        "recipes": f"""## From the parish collection

### Lemon cake

{r.randrange(150, 250)} g flour, {r.randrange(120, 200)} g sugar, three eggs,
the zest of two lemons. Bake at {r.randrange(160, 190)} C for
{r.randrange(30, 50)} minutes. Syrup while warm, not hot.

### Winter soup

Whatever root vegetables are cheap, a bay leaf, and stock. Blend half, leave
half. Better the next day, which is the only reliable rule in this book.

### Note from the editor

Several contributors gave quantities in handfuls. These have been left alone.""",
        "chess": f"""## Bulletin

### League

The first team drew {r.randrange(2,4)}–{r.randrange(2,4)} away and stays second
on board count. The second team lost by default when two boards did not arrive;
please tell the captain **before** the day.

### Club championship

Round {r.randrange(3, 9)} pairings are on the board. Adjournments are not
allowed this season; games unfinished at the time limit go to the arbiter.

### Coaching

Juniors on Saturday mornings. {person} has taken over from the previous coach
and asks that parents stay for the first session.""",
        "library": f"""## Acquisitions

| title | class | copies |
|---|---|---:|
| Regional history, revised edition | 954 | {r.randrange(1,4)} |
| Field guide to grasses | 584 | {r.randrange(1,3)} |
| Introductory statistics | 519 | {r.randrange(2,6)} |
| Two novels in translation | 891 | {r.randrange(1,3)} |

## Withdrawals

Superseded editions of the statistics text are withdrawn once the new copies
are catalogued. Withdrawn stock goes to the book sale, not to the skip.

## Requests

Reader requests are reviewed monthly by {person}. A request refused twice is
explained in writing.""",
    }
    body = bodies.get(key, "## Notes\n\nNothing further this period.")
    return f"""# {title}

*{person} · {year}*

{body}
"""


def variant_doc(i: int, r: random.Random, kind, newer_title: str) -> str:
    """The retired half of a supersession pair. Same subject as its successor,
    older facts, and it lives under ext/archive/."""
    key, ext, title = kind
    full, short, cities, code = pick_company(r)
    city = r.choice(cities)
    person = r.choice(PEOPLE)
    year = r.randrange(2019, 2023)
    return f"""---
title: {title} — {short} ({year}, retired)
owner: {person}
status: retired
effective_date: {year}-{r.randrange(1,13):02d}-{r.randrange(1,28):02d}
---

# {title} — {short} ({year})

> This edition is history. It is kept because auditors ask what the rule was at
> the time, and because customer annexes signed in {year} still quote it.

## What this edition said

1. The {city} site booked slots by telephone and wrote them on the guard
   register. There was no calendar system.
2. The alarm threshold for the {r.choice([p[0] for p in PRODUCTS])} room was
   {r.randrange(4, 10)}.0 C for {r.randrange(20, 60)} continuous minutes —
   longer than the current edition allows.
3. Notification to patient-critical customers was "the same working day". The
   current edition states a number of hours instead.
4. Quarantine was a marked corner of the dispatch bay rather than a separate
   room with its own door log.

## Why it changed

The {year + r.randrange(1,3)} audit found that a "same working day" commitment
could not be evidenced, and that a threshold measured in tens of minutes hid
short repeated breaches that added up. Both were rewritten in the edition that
replaces this one.

## Do not use this document to

- decide a disposition today;
- quote a rate;
- answer a customer question about the current rule.
"""


# --------------------------------------------------------------------------
# The stream
# --------------------------------------------------------------------------
def document(i: int) -> dict:
    """Document `i` of the ext stream. Depends on `i` alone."""
    r = rng_for(i)
    slot = i % 10
    cat = BLOCK[slot]

    if cat == "sibling":
        kind = SIBLING_KINDS[(i * 5 + slot) % len(SIBLING_KINDS)]
        key, ext, title = kind
        # slot 6 is the successor of the variant emitted at slot 5
        supersedes = None
        if slot == 6:
            vkind = SUPERSEDABLE[((i - 1) * 5 + 5) % len(SUPERSEDABLE)]
            supersedes = f"ext/archive/{i-1:05d}-{vkind[0]}-retired.md"
            kind = vkind
            key, ext, title = kind
        body = sibling_doc(i, r, kind, supersedes)
        path = f"ext/sibling/{i:05d}-{key}.{ext}"
        date = a_date(r, 2023, 2026)
    elif cat == "adjacent":
        kind = ADJACENT_KINDS[(i * 3 + slot) % len(ADJACENT_KINDS)]
        body = adjacent_doc(i, r, kind)
        path = f"ext/adjacent/{i:05d}-{kind[0]}.{kind[1]}"
        date = a_date(r, 2022, 2026)
    elif cat == "filler":
        kind = FILLER_KINDS[(i * 7 + slot) % len(FILLER_KINDS)]
        body = filler_doc(i, r, kind)
        path = f"ext/filler/{i:05d}-{kind[0]}.{kind[1]}"
        date = a_date(r, 2021, 2026)
    else:  # variant — retired half of the pair, archived
        kind = SUPERSEDABLE[(i * 5 + 5) % len(SUPERSEDABLE)]
        body = variant_doc(i, r, kind, kind[2])
        path = f"ext/archive/{i:05d}-{kind[0]}-retired.md"
        date = a_date(r, 2019, 2022)

    return {"path": path, "category": cat, "origin": "generated",
            "date": date, "text": body}


def authored() -> list[dict]:
    """Hand-written hard negatives, in filename order, ahead of the stream.

    Each carries a `# golden-ext: <category> <date>` first line (stripped
    before writing) so the manifest can record what it is without a side file.
    """
    out = []
    if not AUTHORED_DIR.is_dir():
        return out
    for p in sorted(AUTHORED_DIR.iterdir()):
        if p.name.startswith(".") or p.is_dir():
            continue
        raw = p.read_text(encoding="utf-8")
        first, _, rest = raw.partition("\n")
        m = re.match(r".*golden-ext:\s*(\w+)\s+(\S+)\s+(\S+?)(?:\s*-->)?\s*$", first)
        if not m:
            raise SystemExit(f"authored doc missing header: {p}")
        cat, date, dest = m.group(1), m.group(2), m.group(3)
        out.append({"path": dest, "category": cat, "origin": "authored",
                    "date": date, "text": rest})
    return out


def stream(n: int) -> list[dict]:
    """The first `n` ext documents: authored ones first, then generated."""
    docs = authored()
    if len(docs) > n:
        return docs[:n]
    i = 0
    while len(docs) < n:
        docs.append(document(i))
        i += 1
    return docs


# --------------------------------------------------------------------------
# The guard
# --------------------------------------------------------------------------
_ENTITY_RE = re.compile(
    "|".join(r"(?<![A-Za-z0-9])" + re.escape(e) + r"(?![A-Za-z0-9])"
             for e in SEED_ENTITIES),
    re.IGNORECASE,
)


def check_corpus(docs: list[dict]) -> list[str]:
    bad = []
    for d in docs:
        for m in _ENTITY_RE.finditer(d["text"]):
            bad.append(f"{d['path']}: seed entity {m.group(0)!r}")
    return bad


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--out")
    ap.add_argument("--count", type=int, default=0)
    ap.add_argument("--check", action="store_true")
    a = ap.parse_args()

    if a.check:
        docs = stream(1000)
        bad = check_corpus(docs)
        if bad:
            print(f"FAIL: {len(bad)} seed-entity leaks")
            for b in bad[:40]:
                print("  " + b)
            return 1
        # prefix stability: the first 80 must be identical when asking for 980
        small = stream(80)
        big = stream(980)[:80]
        assert [d["path"] for d in small] == [d["path"] for d in big], "path drift"
        assert [d["text"] for d in small] == [d["text"] for d in big], "byte drift"
        # category mix at every rung boundary
        for n in (80, 180, 480, 980):
            ds = stream(n)
            from collections import Counter
            c = Counter(d["category"] for d in ds)
            print(f"  rung ext={n}: " + " ".join(
                f"{k}={c[k]} ({100*c[k]/n:.0f}%)" for k in
                ("sibling", "adjacent", "filler", "variant")))
        # Every supersedes: target is inside the same prefix, AND every
        # retired document has exactly one superseder. The second half is the
        # check that was missing: a template that drops the frontmatter key
        # leaves an orphan archive document and no broken target to trip over.
        for n in (80, 180, 480, 980):
            ds = stream(n)
            have = {d["path"] for d in ds}
            targets = []
            for d in ds:
                for m in re.finditer(r"^supersedes:\s*(\S+)", d["text"], re.M):
                    targets.append(m.group(1))
                    if m.group(1) not in have:
                        print(f"FAIL: {d['path']} supersedes missing {m.group(1)} at n={n}")
                        return 1
            retired = [d["path"] for d in ds if d["category"] == "variant"]
            orphan = sorted(set(retired) - set(targets))
            if orphan:
                print(f"FAIL: {len(orphan)} retired document(s) with no superseder "
                      f"at n={n}: {orphan[:5]}")
                return 1
            if len(targets) != len(set(targets)):
                print(f"FAIL: a supersedes: target is claimed twice at n={n}")
                return 1
        print(f"OK: {len(docs)} documents, no seed entity, prefix-stable, "
              f"supersedes closed at every rung")
        return 0

    if not a.out or not a.count:
        ap.error("--out and --count are required unless --check")
    docs = stream(a.count)
    bad = check_corpus(docs)
    if bad:
        print(f"REFUSING TO WRITE: {len(bad)} seed-entity leaks", file=sys.stderr)
        for b in bad[:20]:
            print("  " + b, file=sys.stderr)
        return 1
    out = Path(a.out)
    for d in docs:
        p = out / d["path"]
        p.parent.mkdir(parents=True, exist_ok=True)
        p.write_text(d["text"], encoding="utf-8")
    # a side file the rung build reads for dates/categories/origins
    meta = out / ".ext-manifest.tsv"
    meta.write_text(
        "".join(f"{d['path']}\t{d['category']}\t{d['origin']}\t{d['date']}\t"
                f"{hashlib.sha256(d['text'].encode()).hexdigest()}\n" for d in docs),
        encoding="utf-8")
    print(f"wrote {len(docs)} documents to {out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
