"""The enrichment queue — what fux could not read, written down.

**Why this exists at all.** Before W-86, nothing in fux could *say* "a model
must read this." `fux enrich --plan` derives its worklist from `enrich=true` on
a `.fux/sources/dirs` line — **declared** scope. A decoder returning `None` is a
**discovered** need: an image, a scanned PDF, a deck of pictures, a format
nothing claims. Those had nowhere to go, so they were skipped and forgotten.

**Two files, and the split is Arpit's ruling (2026-08-26): committed queue,
gitignored progress.**

| file | git | why |
|---|---|---|
| `.fux/enrich/queue.tsv` | **committed** | the backlog is a *team* fact — a teammate cloning the repo should see what still needs a model without re-running ingest |
| `.fux/runtime/enrich-progress.tsv` | **gitignored** | which entries *this machine* has worked through is a local fact, and committing it would make two people's progress conflict on every pull |

**The queue is committed, so it is bound by L3 and L2 like any committed byte:**

- **Sorted by path**, always. Walk order is filesystem order, and a queue that
  differed between two machines would make `git status` dirty for no reason.
- **No wall clock.** Nothing here records *when* — a timestamp would make the
  file change on every run and turn a stable backlog into noise.
- **Paths, shas and a reason. Never content.** The whole architecture rests on
  the index holding statistics rather than documents, and a queue that quoted
  the first line of an unreadable file would be the one place that leaked.

⚠ **Not written into `.fux/enrich/` as `<sha>.md`-shaped data.** That directory
is globbed as `<sha>.md` by `enrich.py::prune`, which deletes orphans; a file
that is not a sha would be at the mercy of that glob. `queue.tsv` is checked
against both and is invisible to them, and `tests/ingest/test_queue.py` pins it.
"""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path

QUEUE_REL = ".fux/enrich/queue.tsv"
PROGRESS_REL = ".fux/runtime/enrich-progress.tsv"

_HEADER = (
    "# Documents fux could not read. A model must. Generated by `fux ingest`.\n"
    "# doc_id\tcontent_sha\treason\n"
    "# Sorted by doc_id, no timestamps: this file changes only when the\n"
    "# BACKLOG changes, so a re-run on an unchanged corpus is an empty diff.\n"
)


@dataclass(frozen=True)
class QueueEntry:
    """One document nothing could read.

    `reason` is the decoder's own words — `image/png`, `pdf: no text layer`,
    `no decoder for .heic`. It is what turns a queue into something a human can
    triage rather than a list of paths.
    """

    doc_id: str
    sha: str
    reason: str

    def line(self) -> str:
        return f"{self.doc_id}\t{self.sha}\t{_clean(self.reason)}"


def _clean(text: str) -> str:
    """One line, no tabs — the field separator must survive a decoder's message."""
    return " ".join(str(text).split()).replace("\t", " ")


def render(entries: list[QueueEntry]) -> str:
    """Entries -> the committed file's exact bytes.

    Deduplicated on `doc_id`: one document is one row even if two passes
    reported it. Sorted last, so the caller never has to remember to.
    """
    unique: dict[str, QueueEntry] = {}
    for entry in entries:
        unique[entry.doc_id] = entry
    body = "\n".join(unique[key].line() for key in sorted(unique))
    return _HEADER + (body + "\n" if body else "")


def read(root: Path) -> list[QueueEntry]:
    """Parse the committed queue. A malformed row is skipped, never fatal.

    A hand-edited queue is expected — triage is a human activity — so one bad
    line must not stop an ingest.
    """
    path = root / QUEUE_REL
    if not path.is_file():
        return []
    out: list[QueueEntry] = []
    for line in path.read_text(encoding="utf-8", errors="replace").splitlines():
        if not line.strip() or line.startswith("#"):
            continue
        parts = line.split("\t")
        if len(parts) < 2:
            continue
        out.append(
            QueueEntry(
                doc_id=parts[0], sha=parts[1], reason=parts[2] if len(parts) > 2 else ""
            )
        )
    return sorted(out, key=lambda e: e.doc_id)


def write(root: Path, entries: list[QueueEntry]) -> bool:
    """Write the queue if its bytes changed. `True` when something was written.

    **Identical bytes are not rewritten**, the same rule the index shards
    follow: an ingest over an unchanged corpus must leave `git status` clean, and
    a queue that rewrote itself every run would be the one file that never did.
    """
    path = root / QUEUE_REL
    text = render(entries)
    if path.is_file() and path.read_text(encoding="utf-8") == text:
        return False
    if not entries and not path.is_file():
        return False  # nothing to say and nothing to clean up
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")
    return True


# -- progress, which is local and therefore much simpler --------------------


def read_progress(root: Path) -> set[str]:
    """Doc ids this machine has already handled. Absent file means none."""
    path = root / PROGRESS_REL
    if not path.is_file():
        return set()
    return {
        line.split("\t", 1)[0]
        for line in path.read_text(encoding="utf-8", errors="replace").splitlines()
        if line.strip() and not line.startswith("#")
    }


def mark_done(root: Path, doc_id: str) -> None:
    """Record that this machine has dealt with one queued document.

    Append-only and unsorted **because it is gitignored**: nothing diffs it, so
    the determinism the committed queue owes does not apply, and an append is
    one syscall rather than a read-modify-write.
    """
    path = root / PROGRESS_REL
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("a", encoding="utf-8") as handle:
        handle.write(f"{doc_id}\n")


def pending(root: Path) -> list[QueueEntry]:
    """Queued entries this machine has not yet worked through."""
    done = read_progress(root)
    return [entry for entry in read(root) if entry.doc_id not in done]
