"""`fux self-build` — fux's self-knowledge bundle, generated from fux's own source.

Dogfood: run fux's *own* `$0` AST graph extraction over the `fux/` package + its
`.fux/rules`, and emit a pre-built footprint mirror under `data/self/` (shipped in
the wheel). The `--self` scope on `query`/`explain`/`path`/`recall` then reads this
bundle, so fux can explain its own architecture in any repo with no project `.fux/`.

Deterministic + AST-only + offline: the bundle regenerates byte-identically from
source (a test proves it), so fux's self-knowledge can never silently drift from
fux's code. `meta.extractor` is pinned (fux is 100% Python → stdlib `ast`), keeping
the bundle env-independent regardless of the optional tree-sitter extra.
"""
from __future__ import annotations

import shutil
from pathlib import Path

from fux import config, graph, index, loader, paths

# fux is pure Python, so the non-Python extractor never runs — pin it so the bundle
# is identical whether or not the [ast] extra is installed where it's built.
_PINNED_EXTRACTOR = {"language": "python", "backend": "stdlib-ast"}

_BUNDLE_CONFIG = (
    "# Generated by `fux self-build` — do not edit. The self-knowledge bundle is a\n"
    "# hermetic footprint mirror: no host-global rules, only fux's own.\n"
    "use_global = false\n"
    "packs = []\n"
    'graph_globs = ["fux/**/*.py"]\n'
)


def source_root() -> Path:
    """The fux source checkout (repo root containing the `fux/` package + `.fux/`)."""
    return paths.bundled_data_dir().parent.parent


def bundle_root() -> Path:
    """Where the pre-built self-knowledge footprint lives (in the wheel)."""
    return paths.bundled_data_dir() / "self"


def _build_cfg() -> dict:
    cfg = dict(config.DEFAULTS)
    cfg["use_global"] = False          # hermetic: fux's own rules only
    cfg["packs"] = []
    cfg["graph_globs"] = ["fux/**/*.py"]
    return cfg


def build(dest: Path | None = None) -> dict:
    """Regenerate the self-knowledge bundle from fux's source. Returns a summary."""
    src = source_root()
    dest = dest or bundle_root()
    cfg = _build_cfg()
    rs = loader.resolve(src, cfg)

    g = graph.build(src, rs, cfg)
    g["meta"]["extractor"] = _PINNED_EXTRACTOR     # env-independent, deterministic

    out = dest / ".fux" / "out"
    out.mkdir(parents=True, exist_ok=True)
    (out / "graph.json").write_text(graph.to_json(g), encoding="utf-8")
    (out / "rules.json").write_text(index.render_json(rs), encoding="utf-8")
    (out / "INDEX.md").write_text(index.render_index(rs), encoding="utf-8")

    rules_dst = dest / ".fux" / "rules"
    if rules_dst.exists():
        shutil.rmtree(rules_dst)
    rules_dst.mkdir(parents=True, exist_ok=True)
    src_rules = paths.Footprint(src).rules
    if src_rules.is_dir():
        for f in sorted(src_rules.rglob("*.md")):
            rel = f.relative_to(src_rules)
            target = rules_dst / rel
            target.parent.mkdir(parents=True, exist_ok=True)
            target.write_text(f.read_text(encoding="utf-8"), encoding="utf-8")

    (dest / ".fux" / "config.toml").write_text(_BUNDLE_CONFIG, encoding="utf-8")

    return {"nodes": len(g["nodes"]), "edges": len(g["edges"]),
            "rules": len(rs.rules), "bundle": str(dest)}
