"""Render help from the command registry: grouped `--help`, `fux help <cmd>`,
and the regenerated `docs/cli.md` table — one source of truth, no drift (plan §9).

Stdlib only; deterministic; never a model call.
"""
from __future__ import annotations

from fux import registry

_GROUP_TITLE = {
    "authoring": "Authoring — write & maintain the substrate",
    "verification": "Verification — prove rules still match the code",
    "governance": "Governance — the constitutional tier & enforcement",
    "runtime": "Runtime — read knowledge cheaply, day to day",
}


def grouped_help() -> str:
    """`fux --help` body: commands grouped by `group`, descriptions aligned."""
    width = max((len(c.name) for c in registry.COMMANDS), default=0)
    lines = ["Fux knowledge engine ($0, deterministic). Commands by group:", ""]
    for group, cmds in registry.by_group().items():
        if not cmds:
            continue
        lines.append(_GROUP_TITLE.get(group, group))
        for c in cmds:
            lines.append(f"  {c.name:<{width}}  {c.desc}")
        lines.append("")
    lines.append('Run `fux help <command>` for usage + an example, or '
                 '`fux how "<question>"` to find the right command.')
    return "\n".join(lines)


def command_help(name: str) -> str:
    """`fux help <cmd>` / `fux <cmd> --help` detail: desc + usage + example + related."""
    c = registry.get(name)
    if c is None:
        known = ", ".join(sorted(registry._BY_NAME))
        return f"fux: unknown command '{name}'.\nKnown commands: {known}"
    related = ", ".join(c.related) if c.related else "(none)"
    return (
        f"fux {c.name} — {c.desc}\n"
        f"  group:    {c.group}\n"
        f"  usage:    fux {c.name} ...\n"
        f"  example:  {c.example}\n"
        f"  related:  {related}\n"
    )


# ── docs/cli.md regeneration ────────────────────────────────────────────────

_MARK_BEGIN = "<!-- BEGIN registry-table (generated by fux/clihelp.py — do not edit) -->"
_MARK_END = "<!-- END registry-table -->"


def registry_table() -> str:
    """The grouped Markdown command table embedded into docs/cli.md."""
    rows = ["| Command | Group | What it does | Example |",
            "|---|---|---|---|"]
    for c in registry.COMMANDS:
        rows.append(f"| `{c.name}` | {c.group} | {c.desc} | `{c.example}` |")
    return "\n".join(rows)


def render_cli_md_block() -> str:
    """The full generated block (markers + table) that lives inside docs/cli.md."""
    return f"{_MARK_BEGIN}\n\n{registry_table()}\n\n{_MARK_END}"


def sync_cli_md(text: str) -> str:
    """Return `text` with the generated registry block replaced/inserted."""
    block = render_cli_md_block()
    if _MARK_BEGIN in text and _MARK_END in text:
        head, rest = text.split(_MARK_BEGIN, 1)
        _, tail = rest.split(_MARK_END, 1)
        return head + block + tail
    return text.rstrip() + "\n\n" + block + "\n"
